//! rustcopy console (Slint).
//!
//! Every decision about a backup stays in `robocopy_ingest::{runner, gui_api, sessions}`: this crate
//! only collects a choice, asks the core to plan it, starts the same CLI a scheduled task would, and
//! shows what the core reports. The behaviours it must keep are in CATALOGO_COMPORTAMENTI_GUI.md.
//!
//! One entity, the "lavoro" (SPEC_GUI_SLINT.md 5.0): every copy started here is a session in the
//! core's sessions log, listed in the sidebar with how it went. A row opens its detail, from which it
//! can be repeated or saved as a task.
#![cfg_attr(windows, windows_subsystem = "windows")]

mod form;
mod format;
mod report_rows;
mod run;
mod single_instance;
mod state;

use std::cell::{Cell, RefCell};
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use robocopy_ingest::integrity::HashAlgorithm;
use robocopy_ingest::job_editor::{self, JobDraft};
use robocopy_ingest::sessions::{Session, SessionLog, SessionState, SessionSummary};
use robocopy_ingest::{gui_api, runner};
use slint::winit_030::{winit::event::WindowEvent, EventResult, WinitWindowAccessor};
use slint::{ComponentHandle, ModelRc, SharedString, Timer, TimerMode, VecModel, Weak};

use crate::form::FormValues;
use crate::run::ActiveRun;
use crate::single_instance::Request;
use crate::state::{running_fraction, Generation, RunSlot, Running};

// Code generated by the Slint compiler from ui/*.slint. It unwraps internally; that is not code we
// write or can change, so the unwrap/expect gate (ci.yml, `ui` job) does not apply to it. Everything
// we write stays under the gate.
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod generated {
    slint::include_modules!();
}
use generated::{
    AdviceRow, AppTray, AppWindow, DetailRow, EditForm, HistRow, PropRow, SessionRow, TaskRow,
};

/// Names the mutex and the pipe of the single window (E12).
const INSTANCE_TAG: &str = "rustcopy-ui";
/// How many lavori the sidebar shows.
const LIST_LIMIT: usize = 100;

/// Everything the callbacks share. Lives on the UI thread only.
struct Ctx {
    log: SessionLog,
    slot: RunSlot<ActiveRun>,
    /// The session this window is running now, if any (the core needs it to tell "running" from
    /// "interrupted").
    running_id: RefCell<Option<String>>,
    /// Whether to open the destination folder when the run now going ends clean. A choice about
    /// this run only: it is not part of a copy's settings, so it is not saved with a task.
    open_when_done: Cell<bool>,
    sessions: RefCell<Vec<SessionSummary>>,
    /// Discards a slow report read when the user has opened another lavoro meanwhile (E01).
    details: Generation,
    /// Discards a slow scheduled-task lookup if the list was rebuilt meanwhile.
    schedules: Generation,
    /// Recent throughput samples for the speed chart (MB/s), newest last.
    speeds: RefCell<Vec<f64>>,
    /// The configuration being edited, if the editor is open.
    edit: RefCell<Option<EditState>>,
}

/// What the editor holds between opening a task and saving a proposal.
struct EditState {
    config: PathBuf,
    drafts: Vec<JobDraft>,
    index: usize,
}

fn set_sources(ui: &AppWindow, sources: &[String]) {
    let model: Vec<SharedString> = sources
        .iter()
        .map(|s| SharedString::from(s.as_str()))
        .collect();
    ui.set_sources(ModelRc::new(VecModel::from(model)));
}

/// Adds a folder to the list unless it is already there (case-insensitive, as Windows paths are).
fn push_unique(list: &mut Vec<String>, path: &Path) {
    let text = path.to_string_lossy().into_owned();
    if !list.iter().any(|known| known.eq_ignore_ascii_case(&text)) {
        list.push(text);
    }
}

/// The interface's number for a state (`sessions.slint` documents the mapping).
fn state_number(state: SessionState) -> i32 {
    match state {
        SessionState::Clean => 0,
        SessionState::DryRun => 1,
        SessionState::NeedsLook => 2,
        SessionState::Interrupted => 3,
        SessionState::Running => 4,
    }
}

fn row_for(session: &SessionSummary) -> SessionRow {
    SessionRow {
        id: session.id.as_str().into(),
        sources: format::folder_names(&session.sources).into(),
        dest_name: format::folder_name(&session.dest).into(),
        when: format::when_short(session.started_at).into(),
        files: session.files_copied.to_string().into(),
        size: format::human_bytes(session.bytes_copied).into(),
        state: state_number(session.state),
        saved: session.saved_as.is_some(),
    }
}

/// Rereads the list from the core and shows it; refreshes the open detail too, because a lavoro
/// that was running may just have ended.
fn refresh(ui: &AppWindow, ctx: &Rc<Ctx>) {
    let running = ctx.running_id.borrow().clone();
    let list = ctx.log.list(LIST_LIMIT, running.as_deref());
    let rows: Vec<SessionRow> = list.iter().map(row_for).collect();
    ui.set_sessions(ModelRc::new(VecModel::from(rows)));
    *ctx.sessions.borrow_mut() = list;
    refresh_tasks(ui, ctx);
    if ui.get_page() == 1 {
        let id = ui.get_selected_id().to_string();
        fill_detail(ui, ctx, &id);
    }
}

/// Rereads the saved tasks and pairs each with how its latest run from this console went.
fn refresh_tasks(ui: &AppWindow, ctx: &Rc<Ctx>) {
    let sessions = ctx.sessions.borrow();
    let rows: Vec<TaskRow> = ctx
        .log
        .list_entries(&tasks_dir())
        .into_iter()
        .map(|task| {
            let last = sessions
                .iter()
                .find(|s| s.task.as_deref() == Some(task.path.as_path()));
            TaskRow {
                path: task.path.to_string_lossy().into_owned().into(),
                name: task.name.as_str().into(),
                folders: format!("{}  →  {}", format::folder_names(&task.sources), task.dest)
                    .into(),
                last_state: last.map_or(-1, |s| state_number(s.state)),
                last_when: last
                    .map(|s| format::when_short(s.started_at))
                    .unwrap_or_default()
                    .into(),
                verify: task.verify.map_or("", algorithm_name).into(),
                jobs: i32::try_from(task.jobs).unwrap_or(1),
                saved: task.saved,
                scheduled: false,
            }
        })
        .collect();
    let paths: Vec<PathBuf> = rows
        .iter()
        .map(|row| PathBuf::from(row.path.as_str()))
        .collect();
    ui.set_tasks(ModelRc::new(VecModel::from(rows)));

    // Which of them a Windows scheduled task already runs: asked of `schtasks.exe` on a worker thread
    // (it is slow), and shown when it answers, unless the list was rebuilt meanwhile.
    let ticket = ctx.schedules.next();
    let generation = ctx.schedules.clone();
    let weak = ui.as_weak();
    std::thread::spawn(move || {
        let scheduled: Vec<bool> = paths
            .iter()
            .map(|path| {
                gui_api::schedules_referencing(path)
                    .map(|names| !names.is_empty())
                    .unwrap_or(false)
            })
            .collect();
        let _ = weak.upgrade_in_event_loop(move |ui| {
            if !generation.is_current(ticket) {
                return;
            }
            use slint::Model;
            let model = ui.get_tasks();
            for (index, flag) in scheduled.into_iter().enumerate() {
                if let Some(mut row) = model.row_data(index) {
                    if row.scheduled != flag {
                        row.scheduled = flag;
                        model.set_row_data(index, row);
                    }
                }
            }
        });
    });
}

/// The properties grid for one configuration: every job's settings, grouped, with where each value
/// comes from. All of it is the core's (`gui_api::read_settings`); this only lays it out in rows.
fn property_rows(config: &Path) -> Result<Vec<PropRow>, String> {
    use robocopy_ingest::gui_api::SettingOrigin;
    let jobs = gui_api::read_settings(config).map_err(|e| e.to_string())?;
    let many = jobs.len() > 1;
    let mut rows = Vec::new();
    for job in jobs {
        if many {
            rows.push(PropRow {
                kind: 0,
                key: job.name.as_str().into(),
                value: "".into(),
                origin: 0,
                caution: "".into(),
            });
        }
        for group in job.groups {
            rows.push(PropRow {
                kind: 1,
                key: group.title.as_str().into(),
                value: "".into(),
                origin: 0,
                caution: "".into(),
            });
            for entry in group.entries {
                rows.push(PropRow {
                    kind: 2,
                    key: entry.key.as_str().into(),
                    value: entry.value.as_str().into(),
                    origin: match entry.origin {
                        SettingOrigin::Job => 0,
                        SettingOrigin::Inherited => 1,
                        SettingOrigin::Default => 2,
                    },
                    caution: entry.caution.unwrap_or_default().into(),
                });
            }
        }
    }
    Ok(rows)
}

fn to_slint(form: &FormValues) -> EditForm {
    EditForm {
        name: form.name.as_str().into(),
        source: form.source.as_str().into(),
        dest: form.dest.as_str().into(),
        pattern: form.pattern.as_str().into(),
        threads: form.threads.as_str().into(),
        retries: form.retries.as_str().into(),
        retry_wait_seconds: form.retry_wait_seconds.as_str().into(),
        bandwidth_limit_mbps: form.bandwidth_limit_mbps.as_str().into(),
        verify_integrity: form.verify_integrity,
        fast_verify: form.fast_verify,
        ignore_transient_missing: form.ignore_transient_missing,
        exclude_junctions: form.exclude_junctions,
        compare_baseline: form.compare_baseline,
        dry_run: form.dry_run,
        long_paths: form.long_paths,
        preserve_timestamps: form.preserve_timestamps,
        preserve_acl: form.preserve_acl,
        no_prescan: form.no_prescan,
        mirror: form.mirror,
        hash_algo: form.hash_algo,
        backup_type: form.backup_type,
        keep_generations: form.keep_generations.as_str().into(),
        exclude_files: form.exclude_files.as_str().into(),
        exclude_dirs: form.exclude_dirs.as_str().into(),
        min_age_days: form.min_age_days.as_str().into(),
        max_age_days: form.max_age_days.as_str().into(),
        report_path: form.report_path.as_str().into(),
        log_path: form.log_path.as_str().into(),
        html_report_path: form.html_report_path.as_str().into(),
        encrypt_keyring: form.encrypt_keyring.as_str().into(),
        encrypt_other: form.encrypt_other,
    }
}

fn from_slint(form: EditForm) -> FormValues {
    FormValues {
        name: form.name.to_string(),
        source: form.source.to_string(),
        dest: form.dest.to_string(),
        pattern: form.pattern.to_string(),
        threads: form.threads.to_string(),
        retries: form.retries.to_string(),
        retry_wait_seconds: form.retry_wait_seconds.to_string(),
        bandwidth_limit_mbps: form.bandwidth_limit_mbps.to_string(),
        verify_integrity: form.verify_integrity,
        fast_verify: form.fast_verify,
        ignore_transient_missing: form.ignore_transient_missing,
        exclude_junctions: form.exclude_junctions,
        compare_baseline: form.compare_baseline,
        dry_run: form.dry_run,
        long_paths: form.long_paths,
        preserve_timestamps: form.preserve_timestamps,
        preserve_acl: form.preserve_acl,
        no_prescan: form.no_prescan,
        mirror: form.mirror,
        hash_algo: form.hash_algo,
        backup_type: form.backup_type,
        keep_generations: form.keep_generations.to_string(),
        exclude_files: form.exclude_files.to_string(),
        exclude_dirs: form.exclude_dirs.to_string(),
        min_age_days: form.min_age_days.to_string(),
        max_age_days: form.max_age_days.to_string(),
        report_path: form.report_path.to_string(),
        log_path: form.log_path.to_string(),
        html_report_path: form.html_report_path.to_string(),
        encrypt_keyring: form.encrypt_keyring.to_string(),
        encrypt_other: form.encrypt_other,
    }
}

/// Puts draft number `index` into the editor and records what the form may not widen (the core's
/// rules, shown as disabled controls with their reason; the core remains the one that refuses).
fn load_editor_form(ui: &AppWindow, state: &EditState) {
    let Some(draft) = state.drafts.get(state.index) else {
        return;
    };
    ui.set_form(to_slint(&FormValues::from_draft(draft)));
    ui.set_mirror_was_on(draft.mirror);
    ui.set_retention_was_set(draft.keep_generations.is_some());
    ui.set_edit_message("".into());
    ui.set_edit_ok(false);
    ui.set_edit_job_index(i32::try_from(state.index).unwrap_or(0));
}

/// Number of past runs read for the history page.
const HISTORY_LIMIT: usize = 200;

/// Past runs and the advisor's observations for a configuration, read from the run index that sits
/// beside each job's report. Whether a run was clean, and what the advisor concludes, are the core's
/// (`runner::exit_code_meaning`, `gui_api::read_advice`); the process exit code 0 is the CLI's own
/// contract for success (AGENTS.md rule 12), not robocopy's bitmask.
fn history_rows(config: &Path) -> Result<(Vec<HistRow>, Vec<AdviceRow>, bool), String> {
    use robocopy_ingest::advise::Severity;
    let jobs = gui_api::list_jobs(config).map_err(|e| e.to_string())?;
    let many = jobs.len() > 1;
    let mut runs: Vec<(chrono::DateTime<chrono::Utc>, HistRow)> = Vec::new();
    let mut advice: Vec<AdviceRow> = Vec::new();
    let mut skipped = false;
    for job in &jobs {
        let Some(report) = job.report_path.as_deref() else {
            continue;
        };
        let report = Path::new(report);
        let job_name = job.history_job_name.as_deref();
        let view =
            gui_api::read_history(report, job_name, HISTORY_LIMIT).map_err(|e| e.to_string())?;
        skipped |= view.skipped_lines > 0;
        for run in view.runs {
            let outcome = if run.dry_run {
                1
            } else if run.exit_code == 0 {
                0
            } else {
                2
            };
            runs.push((
                run.timestamp,
                HistRow {
                    job: if many {
                        job.name.as_str().into()
                    } else {
                        "".into()
                    },
                    when: format::when_text(run.timestamp).into(),
                    files: run.files_copied.to_string().into(),
                    size: format::human_bytes(run.bytes_copied).into(),
                    speed: format::human_speed(run.throughput_mbps).into(),
                    meaning: runner::exit_code_meaning(run.exit_code).into(),
                    outcome,
                },
            ));
        }
        if let Ok(found) = gui_api::read_advice(report, job_name) {
            for item in found {
                let prefix = if many {
                    format!("{}: ", job.name)
                } else {
                    String::new()
                };
                advice.push(AdviceRow {
                    severity: match item.severity {
                        Severity::Info => 0,
                        Severity::Suggestion => 1,
                        Severity::Warning => 2,
                    },
                    headline: format!("{prefix}{}", item.headline).into(),
                    evidence: item.evidence.join("  ·  ").into(),
                });
            }
        }
    }
    runs.sort_by_key(|run| std::cmp::Reverse(run.0));
    advice.sort_by_key(|a| std::cmp::Reverse(a.severity));
    Ok((
        runs.into_iter().map(|(_, row)| row).collect(),
        advice,
        skipped,
    ))
}

/// Runs a saved task (or any configuration file) in place, as a lavoro of the list.
fn start_task(ui: &AppWindow, ctx: &Rc<Ctx>, config: &Path) {
    if ctx.slot.with(|run| run.is_running()) == Some(true) {
        ui.set_error(ui.get_busy_text());
        return;
    }
    ctx.open_when_done.set(false);
    match ctx.log.begin_task(config) {
        Ok(session) => run_session(ui, ctx, &session),
        Err(error) => ui.set_error(error.to_string().into()),
    }
}

/// Fills the detail page for `id`. Numbers come from the session summary; the one-line reason for a
/// "needs a look" outcome is read from its report on a worker thread, so a big report never blocks
/// the window.
fn fill_detail(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str) {
    let sessions = ctx.sessions.borrow();
    let Some(session) = sessions.iter().find(|s| s.id == id) else {
        return;
    };
    ui.set_d_state(state_number(session.state));
    ui.set_d_where(format!("{}  →  {}", session.sources.join("; "), session.dest).into());
    ui.set_d_when(format::when_text(session.started_at).into());
    let finished = session.exit_code.is_some();
    ui.set_d_has_numbers(finished && session.state != SessionState::Interrupted);
    ui.set_d_files(session.files_copied.to_string().into());
    ui.set_d_size(format::human_bytes(session.bytes_copied).into());
    ui.set_d_time(format::human_duration(session.elapsed_seconds).into());
    ui.set_d_speed(
        format::human_speed(format::throughput_mbps(
            session.bytes_copied,
            session.elapsed_seconds,
        ))
        .into(),
    );
    // A run of a saved task or of an added file already *is* a configuration: show where it lives
    // instead of offering to save it again.
    ui.set_d_saved(
        session
            .saved_as
            .as_ref()
            .or(session.task.as_ref())
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_default()
            .into(),
    );
    ui.set_d_detail("".into());
    ui.set_d_verify(session.verify.map_or("", algorithm_name).into());
    ui.set_d_has_reports(!session.reports.is_empty());

    if session.state == SessionState::NeedsLook {
        if let Some(report) = session.reports.first().cloned() {
            let ticket = ctx.details.next();
            let generation = ctx.details.clone();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let meaning = gui_api::read_report(&report)
                    .ok()
                    .and_then(|view| view.exit_code_meaning);
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if generation.is_current(ticket) {
                        ui.set_d_detail(meaning.unwrap_or_default().into());
                    }
                });
            });
        }
    }
}

fn select_session(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str) {
    ctx.details.next();
    ui.set_selected_id(id.into());
    ui.set_d_show_technical(false);
    ui.set_d_rows(ModelRc::new(VecModel::from(Vec::<DetailRow>::new())));
    ui.set_saving(false);
    ui.set_save_message("".into());
    ui.set_page(1);
    fill_detail(ui, ctx, id);
}

/// Starts the CLI for a session already in the log and puts the new-copy page into its running state.
fn run_session(ui: &AppWindow, ctx: &Rc<Ctx>, session: &Session) {
    let started = ctx.slot.try_start(|| ActiveRun::spawn(&session.config));
    match started {
        Ok(()) => {
            *ctx.running_id.borrow_mut() = Some(session.id.clone());
            let running_title = ctx
                .log
                .list(1, Some(&session.id))
                .first()
                .map(|s| {
                    format!(
                        "{} → {}",
                        format::folder_names(&s.sources),
                        format::folder_name(&s.dest)
                    )
                })
                .unwrap_or_default();
            ui.set_running_title(running_title.into());
            ui.set_error("".into());
            ui.set_fraction(-1.0);
            ui.set_files_done_text("".into());
            ui.set_current_file("".into());
            ui.set_eta_text("".into());
            ui.set_chart_commands("".into());
            ctx.speeds.borrow_mut().clear();
            ui.set_running(true);
            ui.set_page(0);
        }
        Err(message) => {
            // It never ran: close it in the log instead of leaving a "started" with no end.
            let _ = ctx.log.finish(&session.id, -1);
            ui.set_error(message.into());
        }
    }
    refresh(ui, ctx);
}

/// A copy chosen in the window or repeated from the list. Planning and every refusal are the core's
/// (`runner::plan_copy`, C01, C02).
fn start_copy(
    ui: &AppWindow,
    ctx: &Rc<Ctx>,
    sources: &[PathBuf],
    dest: &str,
    verify: Option<HashAlgorithm>,
) {
    if ctx.slot.with(|run| run.is_running()) == Some(true) {
        ui.set_error(ui.get_busy_text());
        return;
    }
    let planned = runner::plan_copy(sources, Path::new(dest.trim())).and_then(|items| {
        ctx.log
            .begin_with(sources, Path::new(dest.trim()), &items, verify)
    });
    match planned {
        Ok(session) => run_session(ui, ctx, &session),
        Err(error) => ui.set_error(error.to_string().into()),
    }
}

/// The algorithm behind the combo box index (the order of `Strings.algo-*`).
fn algorithm_for(index: i32) -> HashAlgorithm {
    match index {
        1 => HashAlgorithm::Sha256,
        2 => HashAlgorithm::Blake3,
        _ => HashAlgorithm::Xxh3,
    }
}

/// The name shown for a verification (a technical name, not a sentence).
fn algorithm_name(algorithm: HashAlgorithm) -> &'static str {
    match algorithm {
        HashAlgorithm::Xxh3 => "xxHash3",
        HashAlgorithm::Sha256 => "SHA-256",
        HashAlgorithm::Blake3 => "BLAKE3",
    }
}

/// What a person who looked away needs when a copy ends: the taskbar button flashes (nothing to
/// install, nothing that interrupts) and, if asked, the destination folder opens. The folder opens
/// only for a clean run: after a problem the person should read the outcome first.
fn announce_finish(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str, state: Option<SessionState>) {
    use slint::winit_030::winit::window::UserAttentionType;
    ui.window().with_winit_window(|window| {
        if !window.has_focus() {
            window.request_user_attention(Some(UserAttentionType::Informational));
        }
    });
    if ctx.open_when_done.replace(false) && state == Some(SessionState::Clean) {
        let dest = ctx
            .sessions
            .borrow()
            .iter()
            .find(|s| s.id == id)
            .map(|s| s.dest.clone());
        if let Some(dest) = dest {
            open_folder(&dest);
        }
    }
}

/// Opens a folder in Explorer. Failure is silent on purpose: the copy has finished and is reported;
/// a folder that cannot be shown must not turn that into an error.
fn open_folder(path: &str) {
    let _ = std::process::Command::new("explorer.exe").arg(path).spawn();
}

/// The folder saved tasks go to: `Documents\rustcopy\attivita`.
fn tasks_dir() -> PathBuf {
    // `RUSTCOPY_TASKS_DIR` lets a test keep its files out of the real Documents folder.
    if let Some(dir) = std::env::var_os("RUSTCOPY_TASKS_DIR").filter(|v| !v.is_empty()) {
        return PathBuf::from(dir);
    }
    dirs::document_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("rustcopy")
        .join("attivita")
}

/// A file-name-safe proposal for a task name from the first folder of a session.
fn proposed_task_name(session: &SessionSummary) -> String {
    let name = session
        .sources
        .first()
        .map(|p| format::folder_name(p))
        .unwrap_or_default();
    name.chars()
        .filter(|c| !"<>:\"/\\|?*".contains(*c) && !c.is_control())
        .collect::<String>()
        .trim()
        .to_string()
}

fn main() -> Result<(), slint::PlatformError> {
    let args: Vec<String> = std::env::args().skip(1).collect();

    // E12: one window. A second launch hands its request to the first and leaves.
    #[cfg(windows)]
    let _instance = match single_instance::acquire(INSTANCE_TAG) {
        single_instance::Role::Primary(instance) => instance,
        single_instance::Role::Secondary => {
            if let Err(message) =
                single_instance::send(INSTANCE_TAG, &single_instance::encode(&args))
            {
                eprintln!("{message}");
            }
            return Ok(());
        }
    };

    let ui = AppWindow::new()?;
    let sources: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
    let ctx = Rc::new(Ctx {
        log: SessionLog::default_location(),
        slot: RunSlot::default(),
        running_id: RefCell::new(None),
        open_when_done: Cell::new(false),
        sessions: RefCell::new(Vec::new()),
        details: Generation::default(),
        schedules: Generation::default(),
        speeds: RefCell::new(Vec::new()),
        edit: RefCell::new(None),
    });
    refresh(&ui, &ctx);

    // The sidebar.
    {
        let weak = ui.as_weak();
        ui.on_new_copy(move || {
            if let Some(ui) = weak.upgrade() {
                ui.set_page(0);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_select_session(move |id| {
            if let Some(ui) = weak.upgrade() {
                select_session(&ui, &ctx, id.as_str());
            }
        });
    }
    // Repeat: the same folders to the same destination, planned again by the core.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_repeat_session(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let found = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .cloned();
            if let Some(session) = found {
                // A saved task is run again from its file, not re-planned from folders.
                if let Some(task) = session.task.as_deref() {
                    start_task(&ui, &ctx, task);
                    return;
                }
                let chosen: Vec<PathBuf> = session.sources.iter().map(PathBuf::from).collect();
                ctx.open_when_done.set(false);
                start_copy(&ui, &ctx, &chosen, &session.dest, session.verify);
            }
        });
    }
    // Save as task: the name is proposed, the file is written by the core and never overwrites.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_begin_save(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let proposal = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .map(proposed_task_name)
                .unwrap_or_default();
            ui.set_save_name(proposal.into());
            ui.set_save_dir(tasks_dir().to_string_lossy().into_owned().into());
            ui.set_save_message("".into());
            ui.set_saving(true);
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_confirm_save(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let name = ui.get_save_name().to_string();
            match ctx.log.save_as_task(id.as_str(), &tasks_dir(), name.trim()) {
                Ok(path) => {
                    ui.set_save_ok(true);
                    ui.set_save_message(path.to_string_lossy().into_owned().into());
                    ui.set_saving(false);
                    refresh(&ui, &ctx);
                }
                Err(error) => {
                    ui.set_save_ok(false);
                    ui.set_save_message(error.to_string().into());
                }
            }
        });
    }

    // Saved tasks.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_show_tasks(move || {
            if let Some(ui) = weak.upgrade() {
                ui.set_error("".into());
                refresh_tasks(&ui, &ctx);
                ui.set_page(2);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_run_task(move |path| {
            if let Some(ui) = weak.upgrade() {
                start_task(&ui, &ctx, Path::new(path.as_str()));
            }
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_run_config_file(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new()
                    .add_filter("Configurazione TOML", &["toml"])
                    .pick_file();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if let Some(path) = picked {
                        ui.invoke_add_config(path.to_string_lossy().into_owned().into());
                    }
                });
            });
        });
    }

    {
        let weak = ui.as_weak();
        ui.on_show_task_props(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            ui.set_props_title(
                config
                    .file_stem()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default()
                    .into(),
            );
            match property_rows(&config) {
                Ok(rows) => {
                    ui.set_error("".into());
                    ui.set_props(ModelRc::new(VecModel::from(rows)));
                }
                Err(message) => {
                    ui.set_props(ModelRc::new(VecModel::from(Vec::<PropRow>::new())));
                    ui.set_error(message.into());
                }
            }
            ui.set_page(3);
        });
    }

    // Editor (phase 4c): opens a configuration's jobs as drafts; saving writes a proposal beside the
    // file, never over it, and every rule about what a draft may contain is the core's.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_task(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            match job_editor::read_drafts(&config) {
                Ok(drafts) if !drafts.is_empty() => {
                    let names: Vec<SharedString> = drafts
                        .iter()
                        .map(|d| SharedString::from(d.name.as_str()))
                        .collect();
                    ui.set_edit_jobs(ModelRc::new(VecModel::from(names)));
                    ui.set_edit_title(
                        config
                            .file_stem()
                            .map(|n| n.to_string_lossy().into_owned())
                            .unwrap_or_default()
                            .into(),
                    );
                    let state = EditState {
                        config,
                        drafts,
                        index: 0,
                    };
                    load_editor_form(&ui, &state);
                    *ctx.edit.borrow_mut() = Some(state);
                    ui.set_error("".into());
                    ui.set_page(4);
                }
                Ok(_) => ui.set_error("Nessun job da modificare in questo file.".into()),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_select_job(move |index| {
            let Some(ui) = weak.upgrade() else { return };
            if let Some(state) = ctx.edit.borrow_mut().as_mut() {
                state.index = usize::try_from(index)
                    .unwrap_or(0)
                    .min(state.drafts.len().saturating_sub(1));
                load_editor_form(&ui, state);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_save(move || {
            let Some(ui) = weak.upgrade() else { return };
            let guard = ctx.edit.borrow();
            let Some(state) = guard.as_ref() else { return };
            let Some(original) = state.drafts.get(state.index) else {
                return;
            };
            let result = from_slint(ui.get_form())
                .to_draft(original)
                .and_then(|draft| {
                    let out = job_editor::suggest_proposal_path_now(&state.config);
                    job_editor::propose_config_from_path(Some(&state.config), &[draft], &out)
                        .map(|()| out)
                        .map_err(|error| error.to_string())
                });
            match result {
                Ok(out) => {
                    ui.set_edit_ok(true);
                    ui.set_edit_message(out.to_string_lossy().into_owned().into());
                }
                Err(message) => {
                    ui.set_edit_ok(false);
                    ui.set_edit_message(message.into());
                }
            }
        });
    }

    {
        let weak = ui.as_weak();
        ui.on_show_history(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            ui.set_hist_name(
                config
                    .file_stem()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default()
                    .into(),
            );
            match history_rows(&config) {
                Ok((runs, advice, skipped)) => {
                    ui.set_error("".into());
                    ui.set_hist_skipped(skipped);
                    ui.set_hist_runs(ModelRc::new(VecModel::from(runs)));
                    ui.set_hist_advice(ModelRc::new(VecModel::from(advice)));
                }
                Err(message) => {
                    ui.set_hist_runs(ModelRc::new(VecModel::from(Vec::<HistRow>::new())));
                    ui.set_hist_advice(ModelRc::new(VecModel::from(Vec::<AdviceRow>::new())));
                    ui.set_error(message.into());
                }
            }
            ui.set_page(5);
        });
    }

    // Technical report of the selected lavoro: read on a worker thread, discarded if another lavoro is
    // opened meanwhile (E01).
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_toggle_technical(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            if ui.get_d_show_technical() {
                ui.set_d_show_technical(false);
                return;
            }
            ui.set_d_show_technical(true);
            let reports: Vec<PathBuf> = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .map(|s| s.reports.clone())
                .unwrap_or_default();
            let ticket = ctx.details.next();
            let generation = ctx.details.clone();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let many = reports.len() > 1;
                let mut rows: Vec<report_rows::Row> = Vec::new();
                for report in &reports {
                    if many {
                        rows.push(report_rows::Row {
                            kind: report_rows::Kind::Heading,
                            label: report
                                .parent()
                                .and_then(|p| p.file_name())
                                .map(|n| n.to_string_lossy().into_owned())
                                .unwrap_or_default()
                                + " / "
                                + &report
                                    .file_name()
                                    .map(|n| n.to_string_lossy().into_owned())
                                    .unwrap_or_default(),
                            value: String::new(),
                        });
                    }
                    if let Ok(view) = gui_api::read_report(report) {
                        rows.extend(report_rows::rows_for(&view));
                    }
                }
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if generation.is_current(ticket) {
                        let shown: Vec<DetailRow> = rows
                            .into_iter()
                            .map(|row| DetailRow {
                                kind: match row.kind {
                                    report_rows::Kind::Heading => 0,
                                    report_rows::Kind::Line => 1,
                                    report_rows::Kind::Problem => 2,
                                },
                                label: row.label.into(),
                                value: row.value.into(),
                            })
                            .collect();
                        ui.set_d_rows(ModelRc::new(VecModel::from(shown)));
                    }
                });
            });
        });
    }

    // A configuration file the person chose is remembered (never copied or changed); removing takes it
    // off the list and leaves the file.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_add_config(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            match ctx.log.add_config(Path::new(path.as_str())) {
                Ok(()) => {
                    ui.set_error("".into());
                    refresh_tasks(&ui, &ctx);
                }
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_remove_config(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            match ctx.log.remove_config(Path::new(path.as_str())) {
                Ok(()) => refresh_tasks(&ui, &ctx),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }

    // New copy: add folders. The native dialog blocks, so it runs on a worker thread (RNF-07).
    {
        let weak: Weak<AppWindow> = ui.as_weak();
        let sources = sources.clone();
        ui.on_add_folders(move || {
            let sources = sources.clone();
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folders().unwrap_or_default();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                    for path in &picked {
                        push_unique(&mut list, path);
                    }
                    set_sources(&ui, &list);
                    ui.set_error("".into());
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.on_remove_source(move |index| {
            if let Some(ui) = weak.upgrade() {
                let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                if (index as usize) < list.len() {
                    list.remove(index as usize);
                }
                set_sources(&ui, &list);
                ui.set_error("".into());
            }
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_browse_dest(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folder();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if let Some(path) = picked {
                        ui.set_dest(path.to_string_lossy().into_owned().into());
                        ui.set_error("".into());
                    }
                });
            });
        });
    }

    // M13: a folder dropped from Explorer arrives as winit's `DroppedFile`, which Slint does not
    // expose to .slint code (C10).
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.window().on_winit_window_event(move |_window, event| {
            if let WindowEvent::DroppedFile(path) = event {
                if path.is_dir() {
                    if let Some(ui) = weak.upgrade() {
                        let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                        push_unique(&mut list, path);
                        set_sources(&ui, &list);
                        ui.set_error("".into());
                        ui.set_page(0);
                    }
                }
            }
            EventResult::Propagate
        });
    }

    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        let ctx = ctx.clone();
        ui.on_start_copy(move || {
            let Some(ui) = weak.upgrade() else { return };
            let chosen: Vec<PathBuf> = sources
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .iter()
                .map(PathBuf::from)
                .collect();
            let dest = ui.get_dest().to_string();
            let verify = ui.get_verify().then(|| algorithm_for(ui.get_verify_algo()));
            ctx.open_when_done.set(ui.get_open_when_done());
            start_copy(&ui, &ctx, &chosen, &dest, verify);
        });
    }
    {
        let ctx = ctx.clone();
        ui.on_stop_copy(move || {
            ctx.slot.with(|run| run.request_stop());
        });
    }

    // E11/E12: a configuration handed over by the Explorer extension (first or second launch).
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_external_open(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            if ctx.slot.with(|run| run.is_running()) == Some(true) {
                ui.set_error(ui.get_busy_text());
                return;
            }
            ctx.open_when_done.set(false);
            match ctx.log.begin_from_config(Path::new(path.as_str())) {
                Ok(session) => run_session(&ui, &ctx, &session),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    #[cfg(windows)]
    {
        let weak = ui.as_weak();
        single_instance::listen(INSTANCE_TAG, move |message| {
            let request = single_instance::parse(&message);
            let _ = weak.upgrade_in_event_loop(move |ui| {
                let _ = ui.show();
                match request {
                    Some(Request::OpenConfig(path)) => {
                        ui.invoke_external_open(path.to_string_lossy().into_owned().into());
                    }
                    Some(Request::Activate) => {}
                    // Never silent: a refused request is shown, not swallowed.
                    None => ui.set_error(ui.get_refused_request_text()),
                }
            });
        });
    }
    if let Some(path) = single_instance::auto_config_arg(&args) {
        ui.invoke_external_open(path.into());
    }

    // Progress, at 250 ms, on the UI thread: a small file read and `try_wait` (E01, E02). One timer for
    // the one resource, so replies cannot overlap.
    let timer = Timer::default();
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        timer.start(TimerMode::Repeated, Duration::from_millis(250), move || {
            let Some(ui) = weak.upgrade() else { return };
            if let Some(sample) = ctx.slot.with(|run| run.progress()).flatten() {
                ui.set_fraction(running_fraction(sample.fraction()));
                ui.set_files_done_text(sample.files_done.to_string().into());
                ui.set_files_total_text(
                    sample
                        .files_total
                        .map_or("?".to_string(), |t| t.to_string())
                        .into(),
                );
                ui.set_speed_text(format::human_speed(sample.throughput_mbps).into());
                ui.set_batch_label(match (sample.batch_index, sample.batch_total) {
                    (Some(index), Some(total)) if total > 1 => {
                        format!("Job {index} di {total}").into()
                    }
                    _ => "".into(),
                });
                ui.set_eta_text(
                    sample
                        .eta_seconds()
                        .map_or(String::new(), format::human_duration)
                        .into(),
                );
                let mut speeds = ctx.speeds.borrow_mut();
                speeds.push(sample.throughput_mbps);
                let excess = speeds.len().saturating_sub(format::CHART_SAMPLES);
                speeds.drain(..excess);
                ui.set_chart_commands(format::chart_path(&speeds, 240.0, 56.0).into());
                ui.set_current_file(sample.current_file.unwrap_or_default().into());
            }
            if let Some(done) = ctx.slot.with(|run| run.finished()).flatten() {
                ctx.slot.take();
                ui.set_running(false);
                let id = ctx.running_id.borrow_mut().take();
                if let Some(id) = id {
                    let state = ctx.log.finish(&id, done.exit_code);
                    refresh(&ui, &ctx);
                    select_session(&ui, &ctx, &id);
                    announce_finish(&ui, &ctx, &id, state.ok());
                }
            }
        });
    }

    // Tray icon (the `system-tray` feature of Slint must stay enabled): left click or "Apri" brings
    // the window back; "Esci" quits.
    let tray = AppTray::new()?;
    {
        let weak = ui.as_weak();
        tray.on_show_window(move || {
            if let Some(ui) = weak.upgrade() {
                let _ = ui.show();
            }
        });
        tray.on_quit(|| {
            let _ = slint::quit_event_loop();
        });
    }
    tray.show()?;
    if std::env::var_os("RUSTCOPY_UI_DARK").is_some() {
        ui.set_force_dark(true);
    }

    ui.show()?;
    slint::run_event_loop_until_quit()
}
