//! rustcopy console (Slint). Phase 2 foundations of PIANO_GUI_SLINT.md.
//!
//! Every decision about a backup stays in `robocopy_ingest::{runner, gui_api}`: this crate only
//! collects a choice, asks the core to plan it, starts the same CLI a scheduled task would, and shows
//! what the core reports. The behaviours it must keep are listed in CATALOGO_COMPORTAMENTI_GUI.md.
#![cfg_attr(windows, windows_subsystem = "windows")]

mod format;
mod run;
mod single_instance;
mod state;

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use robocopy_ingest::{gui_api, runner};
use slint::winit_030::{winit::event::WindowEvent, EventResult, WinitWindowAccessor};
use slint::{ComponentHandle, ModelRc, SharedString, Timer, TimerMode, VecModel, Weak};

use crate::run::ActiveRun;
use crate::single_instance::Request;
use crate::state::{running_fraction, Generation, RunSlot};

// Code generated by the Slint compiler from ui/*.slint. It unwraps internally; that is not code we
// write or can change, so the unwrap/expect gate (ci.yml, `ui` job) does not apply to it. Everything
// we write stays under the gate.
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod generated {
    slint::include_modules!();
}
use generated::{AppTray, AppWindow};

/// Names the mutex and the pipe of the single window (E12).
const INSTANCE_TAG: &str = "rustcopy-ui";

fn set_sources(ui: &AppWindow, sources: &[String]) {
    let model: Vec<SharedString> = sources
        .iter()
        .map(|s| SharedString::from(s.as_str()))
        .collect();
    ui.set_sources(ModelRc::new(VecModel::from(model)));
}

/// Adds a folder to the list unless it is already there (case-insensitive, as Windows paths are).
fn push_unique(list: &mut Vec<String>, path: &Path) {
    let text = path.to_string_lossy().into_owned();
    if !list.iter().any(|known| known.eq_ignore_ascii_case(&text)) {
        list.push(text);
    }
}

/// Fills the Report page. The pass/fail reading is the core's (`exit_code_is_success`), never derived
/// here from the exit code or its description (G09).
fn apply_report(
    ui: &AppWindow,
    result: Result<gui_api::ReportView, robocopy_ingest::errors::IngestError>,
) {
    match result {
        Ok(view) => {
            let kind = if view.dry_run {
                1
            } else if view.exit_code_is_success.unwrap_or(false) {
                0
            } else {
                2
            };
            ui.set_r_kind(kind);
            ui.set_r_detail(view.exit_code_meaning.clone().unwrap_or_default().into());
            ui.set_r_files(view.files_copied.to_string().into());
            ui.set_r_size(format::human_bytes(view.bytes_copied).into());
            ui.set_r_time(format::human_duration(view.elapsed_seconds).into());
            ui.set_r_speed(format::human_speed(view.throughput_mbps).into());
            ui.set_r_where(format!("{}  ->  {}", view.source, view.dest).into());
            ui.set_has_report(true);
        }
        Err(error) => {
            ui.set_has_report(false);
            ui.set_error(error.to_string().into());
        }
    }
}

/// Reads a report on a worker thread and shows it, unless a newer request has been made meanwhile
/// (E01): a slow read of an old report must never overwrite the one the user opened afterwards.
fn load_report(weak: &Weak<AppWindow>, generation: &Generation, path: PathBuf) {
    let ticket = generation.next();
    let generation = generation.clone();
    let weak = weak.clone();
    std::thread::spawn(move || {
        let result = gui_api::read_report(&path);
        let _ = weak.upgrade_in_event_loop(move |ui| {
            if generation.is_current(ticket) {
                apply_report(&ui, result);
                ui.set_page(1);
            }
        });
    });
}

/// Starts one configuration and puts the Copia page into its running state.
fn start_config(ui: &AppWindow, slot: &RunSlot<ActiveRun>, config: &Path) {
    match slot.try_start(|| ActiveRun::spawn(config)) {
        Ok(()) => {
            ui.set_error("".into());
            ui.set_has_report(false);
            ui.set_fraction(-1.0);
            ui.set_files_done_text("".into());
            ui.set_current_file("".into());
            ui.set_running(true);
            ui.set_page(0);
        }
        Err(message) => ui.set_error(message.into()),
    }
}

fn main() -> Result<(), slint::PlatformError> {
    let args: Vec<String> = std::env::args().skip(1).collect();

    // E12: one window. A second launch hands its request to the first and leaves.
    #[cfg(windows)]
    let _instance = match single_instance::acquire(INSTANCE_TAG) {
        single_instance::Role::Primary(instance) => instance,
        single_instance::Role::Secondary => {
            if let Err(message) =
                single_instance::send(INSTANCE_TAG, &single_instance::encode(&args))
            {
                eprintln!("{message}");
            }
            return Ok(());
        }
    };

    let ui = AppWindow::new()?;
    let sources: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
    let slot: Rc<RunSlot<ActiveRun>> = Rc::new(RunSlot::default());
    let reports = Generation::default();

    // Add folders: the native dialog blocks, so it runs on a worker thread (RNF-07).
    {
        let weak: Weak<AppWindow> = ui.as_weak();
        let sources = sources.clone();
        ui.on_add_folders(move || {
            let sources = sources.clone();
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folders().unwrap_or_default();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                    for path in &picked {
                        push_unique(&mut list, path);
                    }
                    set_sources(&ui, &list);
                    ui.set_error("".into());
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.on_remove_source(move |index| {
            if let Some(ui) = weak.upgrade() {
                let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                if (index as usize) < list.len() {
                    list.remove(index as usize);
                }
                set_sources(&ui, &list);
                ui.set_error("".into());
            }
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_browse_dest(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folder();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if let Some(path) = picked {
                        ui.set_dest(path.to_string_lossy().into_owned().into());
                        ui.set_error("".into());
                    }
                });
            });
        });
    }

    // M13: a folder dropped from Explorer arrives as winit's `DroppedFile`, which Slint does not
    // expose to .slint code (C10).
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.window().on_winit_window_event(move |_window, event| {
            if let WindowEvent::DroppedFile(path) = event {
                if path.is_dir() {
                    if let Some(ui) = weak.upgrade() {
                        let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                        push_unique(&mut list, path);
                        set_sources(&ui, &list);
                        ui.set_error("".into());
                        ui.set_page(0);
                    }
                }
            }
            EventResult::Propagate
        });
    }

    // Start: planning and every refusal are the core's (`runner::plan_copy`, C01, C02).
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        let slot = slot.clone();
        ui.on_start_copy(move || {
            let Some(ui) = weak.upgrade() else { return };
            let chosen: Vec<PathBuf> = sources
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .iter()
                .map(PathBuf::from)
                .collect();
            let dest = ui.get_dest().to_string();
            let planned = (|| -> Result<PathBuf, String> {
                let items = runner::plan_copy(&chosen, Path::new(dest.trim()))
                    .map_err(|e| e.to_string())?;
                let config = runner::shell_drop_config_path().map_err(|e| e.to_string())?;
                runner::write_shell_drop_config(&items, &config).map_err(|e| e.to_string())?;
                Ok(config)
            })();
            match planned {
                Ok(config) => start_config(&ui, &slot, &config),
                Err(message) => ui.set_error(message.into()),
            }
        });
    }
    {
        let slot = slot.clone();
        ui.on_stop_copy(move || {
            slot.with(|run| run.request_stop());
        });
    }
    {
        let weak = ui.as_weak();
        let reports = reports.clone();
        ui.on_open_report(move || {
            let weak = weak.clone();
            let reports = reports.clone();
            std::thread::spawn(move || {
                if let Some(path) = rfd::FileDialog::new()
                    .add_filter("Report JSON", &["json"])
                    .pick_file()
                {
                    load_report(&weak, &reports, path);
                }
            });
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_load_rows(move |count| {
            if let Some(ui) = weak.upgrade() {
                let rows: Vec<SharedString> = (0..count.max(0))
                    .map(|i| {
                        SharedString::from(format!(
                            "D:\\Dati\\Foto\\2026\\IMG_{i:06}.jpg    {} KB",
                            1200 + (i * 37) % 9000
                        ))
                    })
                    .collect();
                ui.set_rows_info(format!("{} righe", rows.len()).into());
                ui.set_rows(ModelRc::new(VecModel::from(rows)));
            }
        });
    }
    // E11/E12: a configuration handed over by the Explorer extension (first or second launch).
    {
        let weak = ui.as_weak();
        let slot = slot.clone();
        ui.on_external_open(move |path| {
            if let Some(ui) = weak.upgrade() {
                start_config(&ui, &slot, Path::new(path.as_str()));
            }
        });
    }
    #[cfg(windows)]
    {
        let weak = ui.as_weak();
        single_instance::listen(INSTANCE_TAG, move |message| {
            let request = single_instance::parse(&message);
            let _ = weak.upgrade_in_event_loop(move |ui| {
                let _ = ui.show();
                match request {
                    Some(Request::OpenConfig(path)) => {
                        ui.invoke_external_open(path.to_string_lossy().into_owned().into());
                    }
                    Some(Request::Activate) => {}
                    // Never silent: a refused request is shown, not swallowed.
                    None => ui.set_error(ui.get_refused_request_text()),
                }
            });
        });
    }
    if let Some(path) = single_instance::auto_config_arg(&args) {
        ui.invoke_external_open(path.into());
    }

    // Progress, at 250 ms, on the UI thread: a small file read and `try_wait` (E01, E02). One timer for
    // the one resource, so replies cannot overlap.
    let timer = Timer::default();
    {
        let weak = ui.as_weak();
        let slot = slot.clone();
        let reports = reports.clone();
        timer.start(TimerMode::Repeated, Duration::from_millis(250), move || {
            let Some(ui) = weak.upgrade() else { return };
            if let Some(sample) = slot.with(|run| run.progress()).flatten() {
                ui.set_fraction(running_fraction(sample.fraction()));
                ui.set_files_done_text(sample.files_done.to_string().into());
                ui.set_files_total_text(
                    sample
                        .files_total
                        .map_or("?".to_string(), |t| t.to_string())
                        .into(),
                );
                ui.set_speed_text(format::human_speed(sample.throughput_mbps).into());
                ui.set_current_file(sample.current_file.unwrap_or_default().into());
            }
            if let Some(done) = slot.with(|run| run.finished()).flatten() {
                slot.take();
                ui.set_running(false);
                match done.report {
                    Some(path) => load_report(&weak, &reports, path),
                    None => {
                        let meaning = runner::exit_code_meaning(done.exit_code.clamp(0, 255) as u8);
                        ui.set_error(format!("{meaning} (codice {})", done.exit_code).into());
                    }
                }
            }
        });
    }

    // Tray icon (the `system-tray` feature of Slint must stay enabled): left click or "Apri" brings
    // the window back; "Esci" quits.
    let tray = AppTray::new()?;
    {
        let weak = ui.as_weak();
        tray.on_show_window(move || {
            if let Some(ui) = weak.upgrade() {
                let _ = ui.show();
            }
        });
        tray.on_quit(|| {
            let _ = slint::quit_event_loop();
        });
    }
    tray.show()?;
    if std::env::var_os("RUSTCOPY_UI_DARK").is_some() {
        ui.set_force_dark(true);
    }

    ui.show()?;
    slint::run_event_loop_until_quit()
}
