//! rustcopy console (Slint).
//!
//! Every decision about a backup stays in `robocopy_ingest::{runner, gui_api, sessions}`: this crate
//! only collects a choice, asks the core to plan it, starts the same CLI a scheduled task would, and
//! shows what the core reports. The behaviours it must keep are in CATALOGO_COMPORTAMENTI_GUI.md.
//!
//! One entity, the "lavoro" (SPEC_GUI_SLINT.md 5.0): every copy started here is a session in the
//! core's sessions log, listed in the sidebar with how it went. A row opens its detail, from which it
//! can be repeated or saved as a task.
#![cfg_attr(windows, windows_subsystem = "windows")]

mod check;
mod csv;
mod form;
mod format;
mod help;
mod move_text;
mod report_rows;
mod run;
mod runs;
mod schedule_form;
mod single_instance;
mod state;
mod suspend;
mod toast;

use std::cell::{Cell, RefCell};
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use robocopy_ingest::integrity::HashAlgorithm;
use robocopy_ingest::job_editor::{self, JobDraft};
use robocopy_ingest::moves::{self, MovePlan, VerifiedCopy};
use robocopy_ingest::safety::{self, Confirmation, SafetyLevel};
use robocopy_ingest::sessions::{
    recent_folders, Session, SessionLog, SessionState, SessionSummary,
};
use robocopy_ingest::{gui_api, runner};
use slint::winit_030::{winit::event::WindowEvent, EventResult, WinitWindowAccessor};
use slint::{ComponentHandle, Model, ModelRc, SharedString, Timer, TimerMode, VecModel, Weak};

use crate::form::FormValues;
use crate::run::ActiveRun;
use crate::runs::{history_csv, passes_filter, RunLine};
use crate::single_instance::Request;
use crate::state::{running_fraction, Generation, RunSlot, Running};

// Code generated by the Slint compiler from ui/*.slint. It unwraps internally; that is not code we
// write or can change, so the unwrap/expect gate (ci.yml, `ui` job) does not apply to it. Everything
// we write stays under the gate.
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod generated {
    slint::include_modules!();
}
use generated::{
    AdviceRow, AppTray, AppWindow, DetailRow, EditForm, HelpRow, HistRow, PropRow, SessionRow,
    TaskRow,
};

/// Names the mutex and the pipe of the single window (E12).
const INSTANCE_TAG: &str = "rustcopy-ui";
/// How many recent folders each chooser offers.
const RECENT_LIMIT: usize = 8;
/// How many lavori the sidebar shows.
const LIST_LIMIT: usize = 100;

/// Everything the callbacks share. Lives on the UI thread only.
struct Ctx {
    log: SessionLog,
    slot: RunSlot<ActiveRun>,
    /// The session this window is running now, if any (the core needs it to tell "running" from
    /// "interrupted").
    running_id: RefCell<Option<String>>,
    /// Whether to open the destination folder when the run now going ends clean. A choice about
    /// this run only: it is not part of a copy's settings, so it is not saved with a task.
    open_when_done: Cell<bool>,
    sessions: RefCell<Vec<SessionSummary>>,
    /// Discards a slow report read when the user has opened another lavoro meanwhile (E01).
    details: Generation,
    /// Discards a slow scheduled-task lookup if the list was rebuilt meanwhile.
    schedules: Generation,
    /// Discards a "Controlla prima" answer once the folders or the destination have changed.
    checks: Generation,
    /// Recent throughput samples for the speed chart (MB/s), newest last.
    speeds: RefCell<Vec<f64>>,
    /// The configuration being edited, if the editor is open.
    edit: RefCell<Option<EditState>>,
    /// Every run of the history page, unfiltered: the filter and the CSV work from this.
    history: RefCell<Vec<RunLine>>,
    /// When the copy now going was paused, if it is: the console resumes it by itself after
    /// `suspend::PAUSE_LIMIT`.
    paused_since: Cell<Option<std::time::Instant>>,
    /// The plan of a move waiting for the person's confirmation: which lavoro, and what it would delete.
    /// Shared with the worker threads that compute and execute it.
    move_plan: Arc<Mutex<Option<(String, MovePlan)>>>,
}

/// What the editor holds between opening a task and saving a proposal.
struct EditState {
    config: PathBuf,
    drafts: Vec<JobDraft>,
    index: usize,
}

fn set_sources(ui: &AppWindow, sources: &[String]) {
    let model: Vec<SharedString> = sources
        .iter()
        .map(|s| SharedString::from(s.as_str()))
        .collect();
    ui.set_sources(ModelRc::new(VecModel::from(model)));
    // What was checked no longer describes this list.
    ui.invoke_clear_check();
}

/// Adds a folder to the list unless it is already there (case-insensitive, as Windows paths are).
fn push_unique(list: &mut Vec<String>, path: &Path) {
    let text = path.to_string_lossy().into_owned();
    if !list.iter().any(|known| known.eq_ignore_ascii_case(&text)) {
        list.push(text);
    }
}

/// The interface's number for a state (`sessions.slint` documents the mapping).
fn state_number(state: SessionState) -> i32 {
    match state {
        SessionState::Clean => 0,
        SessionState::DryRun => 1,
        SessionState::NeedsLook => 2,
        SessionState::Interrupted => 3,
        SessionState::Running => 4,
    }
}

fn row_for(session: &SessionSummary) -> SessionRow {
    SessionRow {
        id: session.id.as_str().into(),
        sources: format::folder_names(&session.sources).into(),
        dest_name: format::folder_name(&session.dest).into(),
        when: format::when_short(session.started_at).into(),
        files: session.files_copied.to_string().into(),
        size: format::human_bytes(session.bytes_copied).into(),
        state: state_number(session.state),
        saved: session.saved_as.is_some(),
    }
}

/// Rereads the list from the core and shows it; refreshes the open detail too, because a lavoro
/// that was running may just have ended.
fn refresh(ui: &AppWindow, ctx: &Rc<Ctx>) {
    let running = ctx.running_id.borrow().clone();
    let list = ctx.log.list(LIST_LIMIT, running.as_deref());
    let rows: Vec<SessionRow> = list.iter().map(row_for).collect();
    ui.set_sessions(ModelRc::new(VecModel::from(rows)));
    let recent = recent_folders(&list, RECENT_LIMIT);
    ui.set_recent_sources(ModelRc::new(VecModel::from(
        recent
            .sources
            .iter()
            .map(|p| SharedString::from(p.as_str()))
            .collect::<Vec<_>>(),
    )));
    ui.set_recent_dests(ModelRc::new(VecModel::from(
        recent
            .dests
            .iter()
            .map(|p| SharedString::from(p.as_str()))
            .collect::<Vec<_>>(),
    )));
    *ctx.sessions.borrow_mut() = list;
    refresh_tasks(ui, ctx);
    if ui.get_page() == 1 {
        let id = ui.get_selected_id().to_string();
        fill_detail(ui, ctx, &id);
    }
}

/// Rereads the saved tasks and pairs each with how its latest run from this console went.
fn refresh_tasks(ui: &AppWindow, ctx: &Rc<Ctx>) {
    let sessions = ctx.sessions.borrow();
    let rows: Vec<TaskRow> = ctx
        .log
        .list_entries(&tasks_dir())
        .into_iter()
        .map(|task| {
            let last = sessions
                .iter()
                .find(|s| s.task.as_deref() == Some(task.path.as_path()));
            TaskRow {
                path: task.path.to_string_lossy().into_owned().into(),
                name: task.name.as_str().into(),
                folders: format!("{}  →  {}", format::folder_names(&task.sources), task.dest)
                    .into(),
                last_state: last.map_or(-1, |s| state_number(s.state)),
                last_when: last
                    .map(|s| format::when_short(s.started_at))
                    .unwrap_or_default()
                    .into(),
                verify: task.verify.map_or("", algorithm_name).into(),
                jobs: i32::try_from(task.jobs).unwrap_or(1),
                saved: task.saved,
                scheduled: false,
            }
        })
        .collect();
    let paths: Vec<PathBuf> = rows
        .iter()
        .map(|row| PathBuf::from(row.path.as_str()))
        .collect();
    ui.set_tasks(ModelRc::new(VecModel::from(rows)));

    // Which of them a Windows scheduled task already runs: asked of `schtasks.exe` on a worker thread
    // (it is slow), and shown when it answers, unless the list was rebuilt meanwhile.
    let ticket = ctx.schedules.next();
    let generation = ctx.schedules.clone();
    let weak = ui.as_weak();
    std::thread::spawn(move || {
        let scheduled: Vec<bool> = paths
            .iter()
            .map(|path| {
                gui_api::schedules_referencing(path)
                    .map(|names| !names.is_empty())
                    .unwrap_or(false)
            })
            .collect();
        let _ = weak.upgrade_in_event_loop(move |ui| {
            if !generation.is_current(ticket) {
                return;
            }
            use slint::Model;
            let model = ui.get_tasks();
            for (index, flag) in scheduled.into_iter().enumerate() {
                if let Some(mut row) = model.row_data(index) {
                    if row.scheduled != flag {
                        row.scheduled = flag;
                        model.set_row_data(index, row);
                    }
                }
            }
        });
    });
}

/// The properties grid for one configuration: every job's settings, grouped, with where each value
/// comes from. All of it is the core's (`gui_api::read_settings`); this only lays it out in rows.
fn property_rows(config: &Path) -> Result<Vec<PropRow>, String> {
    use robocopy_ingest::gui_api::SettingOrigin;
    let jobs = gui_api::read_settings(config).map_err(|e| e.to_string())?;
    let many = jobs.len() > 1;
    let mut rows = Vec::new();
    for job in jobs {
        if many {
            rows.push(PropRow {
                kind: 0,
                key: job.name.as_str().into(),
                value: "".into(),
                origin: 0,
                caution: "".into(),
            });
        }
        for group in job.groups {
            rows.push(PropRow {
                kind: 1,
                key: group.title.as_str().into(),
                value: "".into(),
                origin: 0,
                caution: "".into(),
            });
            for entry in group.entries {
                rows.push(PropRow {
                    kind: 2,
                    key: entry.key.as_str().into(),
                    value: entry.value.as_str().into(),
                    origin: match entry.origin {
                        SettingOrigin::Job => 0,
                        SettingOrigin::Inherited => 1,
                        SettingOrigin::Default => 2,
                    },
                    caution: entry.caution.unwrap_or_default().into(),
                });
            }
        }
    }
    Ok(rows)
}

fn to_slint(form: &FormValues) -> EditForm {
    EditForm {
        name: form.name.as_str().into(),
        source: form.source.as_str().into(),
        dest: form.dest.as_str().into(),
        pattern: form.pattern.as_str().into(),
        threads: form.threads.as_str().into(),
        retries: form.retries.as_str().into(),
        retry_wait_seconds: form.retry_wait_seconds.as_str().into(),
        bandwidth_limit_mbps: form.bandwidth_limit_mbps.as_str().into(),
        verify_integrity: form.verify_integrity,
        fast_verify: form.fast_verify,
        ignore_transient_missing: form.ignore_transient_missing,
        exclude_junctions: form.exclude_junctions,
        compare_baseline: form.compare_baseline,
        dry_run: form.dry_run,
        long_paths: form.long_paths,
        preserve_timestamps: form.preserve_timestamps,
        preserve_acl: form.preserve_acl,
        no_prescan: form.no_prescan,
        mirror: form.mirror,
        hash_algo: form.hash_algo,
        backup_type: form.backup_type,
        keep_generations: form.keep_generations.as_str().into(),
        exclude_files: form.exclude_files.as_str().into(),
        exclude_dirs: form.exclude_dirs.as_str().into(),
        min_age_days: form.min_age_days.as_str().into(),
        max_age_days: form.max_age_days.as_str().into(),
        report_path: form.report_path.as_str().into(),
        log_path: form.log_path.as_str().into(),
        html_report_path: form.html_report_path.as_str().into(),
        encrypt_keyring: form.encrypt_keyring.as_str().into(),
        encrypt_other: form.encrypt_other,
    }
}

fn from_slint(form: EditForm) -> FormValues {
    FormValues {
        name: form.name.to_string(),
        source: form.source.to_string(),
        dest: form.dest.to_string(),
        pattern: form.pattern.to_string(),
        threads: form.threads.to_string(),
        retries: form.retries.to_string(),
        retry_wait_seconds: form.retry_wait_seconds.to_string(),
        bandwidth_limit_mbps: form.bandwidth_limit_mbps.to_string(),
        verify_integrity: form.verify_integrity,
        fast_verify: form.fast_verify,
        ignore_transient_missing: form.ignore_transient_missing,
        exclude_junctions: form.exclude_junctions,
        compare_baseline: form.compare_baseline,
        dry_run: form.dry_run,
        long_paths: form.long_paths,
        preserve_timestamps: form.preserve_timestamps,
        preserve_acl: form.preserve_acl,
        no_prescan: form.no_prescan,
        mirror: form.mirror,
        hash_algo: form.hash_algo,
        backup_type: form.backup_type,
        keep_generations: form.keep_generations.to_string(),
        exclude_files: form.exclude_files.to_string(),
        exclude_dirs: form.exclude_dirs.to_string(),
        min_age_days: form.min_age_days.to_string(),
        max_age_days: form.max_age_days.to_string(),
        report_path: form.report_path.to_string(),
        log_path: form.log_path.to_string(),
        html_report_path: form.html_report_path.to_string(),
        encrypt_keyring: form.encrypt_keyring.to_string(),
        encrypt_other: form.encrypt_other,
    }
}

/// Puts draft number `index` into the editor and records what the form may not widen (the core's
/// rules, shown as disabled controls with their reason; the core remains the one that refuses).
fn load_editor_form(ui: &AppWindow, state: &EditState) {
    let Some(draft) = state.drafts.get(state.index) else {
        return;
    };
    ui.set_form(to_slint(&FormValues::from_draft(draft)));
    ui.set_mirror_was_on(draft.mirror);
    ui.set_retention_was_set(draft.keep_generations.is_some());
    ui.set_edit_message("".into());
    ui.set_edit_ok(false);
    ui.set_edit_job_index(i32::try_from(state.index).unwrap_or(0));
}

/// Number of past runs read for the history page.
const HISTORY_LIMIT: usize = 200;

/// A run as the list row draws it.
fn hist_row(run: &RunLine) -> HistRow {
    HistRow {
        job: run.job.as_str().into(),
        when: format::when_text(run.at).into(),
        files: run.files.to_string().into(),
        size: format::human_bytes(run.bytes).into(),
        speed: format::human_speed(run.throughput_mbps).into(),
        meaning: run.meaning.as_str().into(),
        outcome: run.outcome,
    }
}

/// What the history page holds: the runs, the advisor's observations, and whether any index line was
/// unreadable.
struct HistoryData {
    runs: Vec<RunLine>,
    advice: Vec<AdviceRow>,
    skipped: bool,
}

/// Reads one report's run index and the advisor's observations about it into `data`. Whether a run
/// was clean, and what the advisor concludes, are the core's (`runner::exit_code_meaning`,
/// `gui_api::read_advice`); the process exit code 0 is the CLI's own contract for success (AGENTS.md
/// rule 12), not robocopy's bitmask. `label` names the job when several share the page.
fn read_runs(
    report: &Path,
    job_name: Option<&str>,
    label: &str,
    data: &mut HistoryData,
) -> Result<(), String> {
    use robocopy_ingest::advise::Severity;
    let view = gui_api::read_history(report, job_name, HISTORY_LIMIT).map_err(|e| e.to_string())?;
    data.skipped |= view.skipped_lines > 0;
    for run in view.runs {
        let outcome = if run.dry_run {
            1
        } else if run.exit_code == 0 {
            0
        } else {
            2
        };
        data.runs.push(RunLine {
            at: run.timestamp,
            job: label.to_string(),
            files: run.files_copied,
            bytes: run.bytes_copied,
            throughput_mbps: run.throughput_mbps,
            exit_code: i32::from(run.exit_code),
            meaning: runner::exit_code_meaning(run.exit_code).to_string(),
            outcome,
        });
    }
    if let Ok(found) = gui_api::read_advice(report, job_name) {
        for item in found {
            let prefix = if label.is_empty() {
                String::new()
            } else {
                format!("{label}: ")
            };
            data.advice.push(AdviceRow {
                severity: match item.severity {
                    Severity::Info => 0,
                    Severity::Suggestion => 1,
                    Severity::Warning => 2,
                },
                headline: format!("{prefix}{}", item.headline).into(),
                evidence: item.evidence.join("  ·  ").into(),
            });
        }
    }
    Ok(())
}

fn finish_history(mut data: HistoryData) -> HistoryData {
    data.runs.sort_by_key(|run| std::cmp::Reverse(run.at));
    data.advice.sort_by_key(|a| std::cmp::Reverse(a.severity));
    data
}

/// Past runs for a configuration, from the run index that sits beside each job's report.
fn history_rows(config: &Path) -> Result<HistoryData, String> {
    let jobs = gui_api::list_jobs(config).map_err(|e| e.to_string())?;
    let many = jobs.len() > 1;
    let mut data = HistoryData {
        runs: Vec::new(),
        advice: Vec::new(),
        skipped: false,
    };
    for job in &jobs {
        let Some(report) = job.report_path.as_deref() else {
            continue;
        };
        let label = if many { job.name.as_str() } else { "" };
        read_runs(
            Path::new(report),
            job.history_job_name.as_deref(),
            label,
            &mut data,
        )?;
    }
    Ok(finish_history(data))
}

/// Past runs for a single report file chosen from disk: its index is the one beside it.
fn history_of_report(report: &Path) -> Result<HistoryData, String> {
    let mut data = HistoryData {
        runs: Vec::new(),
        advice: Vec::new(),
        skipped: false,
    };
    read_runs(report, None, "", &mut data)?;
    Ok(finish_history(data))
}

/// Shows the history page's runs through the current filter.
fn apply_history_filter(ui: &AppWindow, ctx: &Rc<Ctx>) {
    let filter = ui.get_hist_filter();
    let shown: Vec<HistRow> = ctx
        .history
        .borrow()
        .iter()
        .filter(|run| passes_filter(filter, run))
        .map(hist_row)
        .collect();
    ui.set_hist_runs(ModelRc::new(VecModel::from(shown)));
}

/// Puts `result` on the history page, or the reason it could not be read.
fn show_history_page(
    ui: &AppWindow,
    ctx: &Rc<Ctx>,
    name: String,
    result: Result<HistoryData, String>,
) {
    ui.set_hist_name(name.into());
    ui.set_hist_filter(0);
    ui.set_hist_message("".into());
    match result {
        Ok(data) => {
            ui.set_error("".into());
            ui.set_hist_skipped(data.skipped);
            ui.set_hist_advice(ModelRc::new(VecModel::from(data.advice)));
            *ctx.history.borrow_mut() = data.runs;
        }
        Err(message) => {
            ui.set_hist_advice(ModelRc::new(VecModel::from(Vec::<AdviceRow>::new())));
            ctx.history.borrow_mut().clear();
            ui.set_error(message.into());
        }
    }
    apply_history_filter(ui, ctx);
    ui.set_page(5);
}

/// A line of the technical report as the interface draws it.
fn detail_row(row: report_rows::Row) -> DetailRow {
    DetailRow {
        kind: match row.kind {
            report_rows::Kind::Heading => 0,
            report_rows::Kind::Line => 1,
            report_rows::Kind::Problem => 2,
        },
        label: row.label.into(),
        value: row.value.into(),
    }
}

/// Runs a saved task (or any configuration file) in place, as a lavoro of the list.
fn start_task(ui: &AppWindow, ctx: &Rc<Ctx>, config: &Path) {
    if ctx.slot.with(|run| run.is_running()) == Some(true) {
        ui.set_error(ui.get_busy_text());
        return;
    }
    ctx.open_when_done.set(false);
    match ctx.log.begin_task(config) {
        Ok(session) => run_session(ui, ctx, &session, false),
        Err(error) => ui.set_error(error.to_string().into()),
    }
}

/// Fills the detail page for `id`. Numbers come from the session summary; the one-line reason for a
/// "needs a look" outcome is read from its report on a worker thread, so a big report never blocks
/// the window.
fn fill_detail(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str) {
    let sessions = ctx.sessions.borrow();
    let Some(session) = sessions.iter().find(|s| s.id == id) else {
        return;
    };
    ui.set_d_state(state_number(session.state));
    ui.set_d_where(format!("{}  →  {}", session.sources.join("; "), session.dest).into());
    ui.set_d_when(format::when_text(session.started_at).into());
    let finished = session.exit_code.is_some();
    ui.set_d_has_numbers(finished && session.state != SessionState::Interrupted);
    ui.set_d_files(session.files_copied.to_string().into());
    ui.set_d_size(format::human_bytes(session.bytes_copied).into());
    ui.set_d_time(format::human_duration(session.elapsed_seconds).into());
    ui.set_d_speed(
        format::human_speed(format::throughput_mbps(
            session.bytes_copied,
            session.elapsed_seconds,
        ))
        .into(),
    );
    // A run of a saved task or of an added file already *is* a configuration: show where it lives
    // instead of offering to save it again.
    ui.set_d_saved(
        session
            .saved_as
            .as_ref()
            .or(session.task.as_ref())
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_default()
            .into(),
    );
    ui.set_d_detail("".into());
    ui.set_d_verify(session.verify.map_or("", algorithm_name).into());
    ui.set_d_has_reports(!session.reports.is_empty());
    // The second step of a move: offered once the copy ended clean and the originals are still there.
    let pending = ctx
        .move_plan
        .lock()
        .unwrap_or_else(|p| p.into_inner())
        .as_ref()
        .is_some_and(|(plan_id, _)| plan_id == id);
    match (session.moving, session.state, session.moved) {
        (true, _, Some((deleted, kept))) => {
            ui.set_d_move(3);
            ui.set_d_move_text(
                format!("Originali cancellati: {deleted} file. Rimasti al loro posto: {kept}.")
                    .into(),
            );
        }
        (true, SessionState::Clean, None) if !pending => {
            ui.set_d_move(1);
            ui.set_d_move_text("".into());
        }
        (true, SessionState::Clean, None) => ui.set_d_move(2),
        _ => {
            ui.set_d_move(0);
            ui.set_d_move_text("".into());
        }
    }
    // An interrupted run left a checkpoint in its folder: offer to continue it (newest first).
    let checkpoint =
        if session.state == SessionState::Interrupted || session.state == SessionState::NeedsLook {
            ctx.log.checkpoints_of(id).into_iter().next()
        } else {
            None
        };
    ui.set_d_resume(checkpoint.map(|c| c.path).unwrap_or_default().into());

    if session.state == SessionState::NeedsLook {
        if let Some(report) = session.reports.first().cloned() {
            let ticket = ctx.details.next();
            let generation = ctx.details.clone();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let meaning = gui_api::read_report(&report)
                    .ok()
                    .and_then(|view| view.exit_code_meaning);
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if generation.is_current(ticket) {
                        ui.set_d_detail(meaning.unwrap_or_default().into());
                    }
                });
            });
        }
    }
}

fn select_session(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str) {
    ctx.details.next();
    ui.set_selected_id(id.into());
    ui.set_d_show_technical(false);
    ui.set_d_rows(ModelRc::new(VecModel::from(Vec::<DetailRow>::new())));
    ui.set_saving(false);
    ui.set_save_message("".into());
    ui.set_error("".into());
    ui.set_page(1);
    fill_detail(ui, ctx, id);
}

/// What the restore preview page says about itself.
const RESTORE_NOTE: &str = "Simulazione: non è stato copiato nulla. Qui sotto c'è ciò che un ripristino copierebbe dalla destinazione verso la sorgente di quella copia.";

/// Runs a restore preview off the window's thread and shows it on the report page.
fn start_restore_preview(ui: &AppWindow, report: PathBuf, workdir: Option<PathBuf>) {
    ui.set_report_busy(true);
    ui.set_error("".into());
    let weak = ui.as_weak();
    std::thread::spawn(move || {
        let outcome = std::env::current_exe()
            .map_err(|e| e.to_string())
            .and_then(|exe| runner::cli_beside(&exe).map_err(|e| e.to_string()))
            .and_then(|cli| {
                gui_api::preview_restore(&cli, &report, workdir.as_deref())
                    .map_err(|e| e.to_string())
            });
        let report_text = report.to_string_lossy().into_owned();
        let workdir_text = workdir
            .map(|d| d.to_string_lossy().into_owned())
            .unwrap_or_default();
        let _ = weak.upgrade_in_event_loop(move |ui| {
            ui.set_report_busy(false);
            match outcome {
                Ok(view) => {
                    let shown: Vec<DetailRow> = report_rows::rows_for(&view)
                        .into_iter()
                        .map(detail_row)
                        .collect();
                    ui.set_report_name("anteprima".into());
                    ui.set_report_note(RESTORE_NOTE.into());
                    ui.set_report_path(report_text.into());
                    ui.set_report_workdir(workdir_text.into());
                    ui.set_report_rows(ModelRc::new(VecModel::from(shown)));
                    ui.set_page(6);
                }
                Err(message) => ui.set_error(message.into()),
            }
        });
    });
}

/// Starts the CLI for a session already in the log and puts the new-copy page into its running state.
fn run_session(ui: &AppWindow, ctx: &Rc<Ctx>, session: &Session, resume: bool) {
    let started = ctx.slot.try_start(|| {
        if resume {
            ActiveRun::spawn_resume(&session.config)
        } else {
            ActiveRun::spawn(&session.config)
        }
    });
    match started {
        Ok(()) => {
            *ctx.running_id.borrow_mut() = Some(session.id.clone());
            let running_title = ctx
                .log
                .list(1, Some(&session.id))
                .first()
                .map(|s| {
                    format!(
                        "{} → {}",
                        format::folder_names(&s.sources),
                        format::folder_name(&s.dest)
                    )
                })
                .unwrap_or_default();
            ui.set_running_title(running_title.into());
            ui.set_error("".into());
            ui.set_fraction(-1.0);
            ui.set_files_done_text("".into());
            ui.set_current_file("".into());
            ui.set_eta_text("".into());
            ui.set_chart_commands("".into());
            ctx.speeds.borrow_mut().clear();
            ui.set_running(true);
            ui.set_page(0);
        }
        Err(message) => {
            // It never ran: close it in the log instead of leaving a "started" with no end.
            let _ = ctx.log.finish(&session.id, -1);
            ui.set_error(message.into());
        }
    }
    refresh(ui, ctx);
}

/// A copy chosen in the window or repeated from the list. Planning and every refusal are the core's
/// (`runner::plan_copy`, C01, C02).
fn start_copy(
    ui: &AppWindow,
    ctx: &Rc<Ctx>,
    sources: &[PathBuf],
    dest: &str,
    verify: Option<HashAlgorithm>,
) {
    if ctx.slot.with(|run| run.is_running()) == Some(true) {
        ui.set_error(ui.get_busy_text());
        return;
    }
    let moving = ui.get_move_mode();
    let planned = runner::plan_copy_with_files(sources, Path::new(dest.trim())).and_then(|items| {
        if moving {
            // A move is always verified; the core refuses it below the Standard level.
            let level = safety::load(&robocopy_ingest::sessions::data_dir());
            ctx.log.begin_move(
                level,
                sources,
                Path::new(dest.trim()),
                &items,
                verify.unwrap_or(HashAlgorithm::Xxh3),
            )
        } else {
            ctx.log
                .begin_with(sources, Path::new(dest.trim()), &items, verify)
        }
    });
    match planned {
        Ok(session) => run_session(ui, ctx, &session, false),
        Err(error) => ui.set_error(error.to_string().into()),
    }
}

/// The algorithm behind the combo box index (the order of `Strings.algo-*`).
fn algorithm_for(index: i32) -> HashAlgorithm {
    match index {
        1 => HashAlgorithm::Sha256,
        2 => HashAlgorithm::Blake3,
        _ => HashAlgorithm::Xxh3,
    }
}

/// The name shown for a verification (a technical name, not a sentence).
fn algorithm_name(algorithm: HashAlgorithm) -> &'static str {
    match algorithm {
        HashAlgorithm::Xxh3 => "xxHash3",
        HashAlgorithm::Sha256 => "SHA-256",
        HashAlgorithm::Blake3 => "BLAKE3",
    }
}

/// What a person who looked away needs when a copy ends: the taskbar button flashes (nothing to
/// install, nothing that interrupts) and, if asked, the destination folder opens. The folder opens
/// only for a clean run: after a problem the person should read the outcome first.
fn announce_finish(ui: &AppWindow, ctx: &Rc<Ctx>, id: &str, state: Option<SessionState>) {
    use slint::winit_030::winit::window::UserAttentionType;
    let mut looked_away = false;
    ui.window().with_winit_window(|window| {
        if !window.has_focus() {
            looked_away = true;
            window.request_user_attention(Some(UserAttentionType::Informational));
        }
    });
    // The system notification only when the person is elsewhere: with the window in front the lavoro
    // already shows its outcome. Windows drops it when the program has no registered identity.
    if looked_away {
        if let Some(text) = ctx
            .sessions
            .borrow()
            .iter()
            .find(|s| s.id == id)
            .and_then(|s| toast_text(s, state))
        {
            toast::show("rustcopy", &text);
        }
    }
    if ctx.open_when_done.replace(false) && state == Some(SessionState::Clean) {
        let dest = ctx
            .sessions
            .borrow()
            .iter()
            .find(|s| s.id == id)
            .map(|s| s.dest.clone());
        if let Some(dest) = dest {
            open_folder(&dest);
        }
    }
}

/// The line of the end-of-copy notification: what was copied and how it went, or nothing when there is
/// nothing to say (a run still going, or one stopped by the person).
fn toast_text(session: &SessionSummary, state: Option<SessionState>) -> Option<String> {
    let place = format!(
        "{} → {}",
        format::folder_names(&session.sources),
        format::folder_name(&session.dest)
    );
    match state? {
        SessionState::Clean => Some(format!(
            "{place}: copia riuscita, {} file ({}).",
            session.files_copied,
            format::human_bytes(session.bytes_copied)
        )),
        SessionState::DryRun => Some(format!("{place}: simulazione terminata.")),
        SessionState::NeedsLook => Some(format!("{place}: da controllare.")),
        SessionState::Running | SessionState::Interrupted => None,
    }
}

/// Asks the core for a schedule command (re-reading the safety level from disk, so a stale window cannot
/// act on a level that was lowered meanwhile), runs the command line with it off the window's thread and
/// shows what happened. A refusal from the core is shown as it is.
fn run_schedule_command<F>(ui: &AppWindow, build: F)
where
    F: FnOnce(SafetyLevel) -> Result<Vec<String>, robocopy_ingest::errors::IngestError>
        + Send
        + 'static,
{
    ui.set_sch_busy(true);
    ui.set_sch_message("".into());
    let weak = ui.as_weak();
    std::thread::spawn(move || {
        let level = safety::load(&robocopy_ingest::sessions::data_dir());
        let outcome = build(level)
            .map_err(|e| e.to_string())
            .and_then(|args| run::run_cli_once(&args));
        let _ = weak.upgrade_in_event_loop(move |ui| {
            ui.set_sch_busy(false);
            match outcome {
                Ok((0, tail)) => {
                    ui.set_sch_ok(true);
                    ui.set_sch_message(tail.into());
                    // The badge on the task list comes from Task Scheduler itself.
                    ui.invoke_show_tasks();
                    ui.set_page(10);
                }
                Ok((code, tail)) => {
                    ui.set_sch_ok(false);
                    ui.set_sch_message(
                        format!("Non è andata a buon fine (codice {code}).\n{tail}").into(),
                    );
                }
                Err(message) => {
                    ui.set_sch_ok(false);
                    ui.set_sch_message(message.into());
                }
            }
        });
    });
}

/// The plan for the second step of a move: the report must prove the copy was verified, the destination
/// folders are recomputed from the sources exactly as the copy did, and the core looks at the disk.
fn plan_a_move(session: &SessionSummary) -> Result<MovePlan, String> {
    let report = session.reports.first().ok_or_else(|| {
        "Questa copia non ha lasciato un report: non posso provare che sia verificata.".to_string()
    })?;
    let view = gui_api::read_report(report).map_err(|e| e.to_string())?;
    let proof = VerifiedCopy::from_report(&view).map_err(|e| e.to_string())?;
    let sources: Vec<PathBuf> = session.sources.iter().map(PathBuf::from).collect();
    let pairs = runner::plan_copy_with_files(&sources, Path::new(&session.dest))
        .map_err(|e| e.to_string())?;
    let level = safety::load(&robocopy_ingest::sessions::data_dir());
    moves::plan_move(level, &pairs, proof).map_err(|e| e.to_string())
}

/// The index of a level in the combo box (the order of its model).
fn level_index(level: SafetyLevel) -> i32 {
    match level {
        SafetyLevel::Prudent => 0,
        SafetyLevel::Standard => 1,
        SafetyLevel::Expert => 2,
    }
}

fn level_for(index: i32) -> SafetyLevel {
    match index {
        1 => SafetyLevel::Standard,
        2 => SafetyLevel::Expert,
        _ => SafetyLevel::Prudent,
    }
}

/// Shows the level in force in the status button and on the safety page.
fn show_safety(ui: &AppWindow) {
    let level = safety::load(&robocopy_ingest::sessions::data_dir());
    ui.set_safety_level(level_index(level));
    ui.set_safety_level_name(level.name().into());
    ui.set_safety_pick(level_index(level));
    ui.set_safety_unlocks(level.unlocks().into());
    ui.set_can_schedule(level.can_prepare_schedules());
    ui.set_can_move(level.can_move());
    if !level.can_move() {
        ui.set_move_mode(false);
    }
}

/// Opens a folder in Explorer. Failure is silent on purpose: the copy has finished and is reported;
/// a folder that cannot be shown must not turn that into an error.
fn open_folder(path: &str) {
    let _ = std::process::Command::new("explorer.exe").arg(path).spawn();
}

/// The folder saved tasks go to: `Documents\rustcopy\attivita`.
fn tasks_dir() -> PathBuf {
    // `RUSTCOPY_TASKS_DIR` lets a test keep its files out of the real Documents folder.
    if let Some(dir) = std::env::var_os("RUSTCOPY_TASKS_DIR").filter(|v| !v.is_empty()) {
        return PathBuf::from(dir);
    }
    dirs::document_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("rustcopy")
        .join("attivita")
}

/// A file-name-safe proposal for a task name from the first folder of a session.
fn proposed_task_name(session: &SessionSummary) -> String {
    let name = session
        .sources
        .first()
        .map(|p| format::folder_name(p))
        .unwrap_or_default();
    name.chars()
        .filter(|c| !"<>:\"/\\|?*".contains(*c) && !c.is_control())
        .collect::<String>()
        .trim()
        .to_string()
}

fn main() -> Result<(), slint::PlatformError> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // The identity the end-of-copy notification belongs to (the installer registers the same one).
    toast::set_process_identity();

    // E12: one window. A second launch hands its request to the first and leaves.
    #[cfg(windows)]
    let _instance = match single_instance::acquire(INSTANCE_TAG) {
        single_instance::Role::Primary(instance) => instance,
        single_instance::Role::Secondary => {
            if let Err(message) =
                single_instance::send(INSTANCE_TAG, &single_instance::encode(&args))
            {
                eprintln!("{message}");
            }
            return Ok(());
        }
    };

    let ui = AppWindow::new()?;
    let sources: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
    let ctx = Rc::new(Ctx {
        log: SessionLog::default_location(),
        slot: RunSlot::default(),
        running_id: RefCell::new(None),
        open_when_done: Cell::new(false),
        sessions: RefCell::new(Vec::new()),
        details: Generation::default(),
        schedules: Generation::default(),
        checks: Generation::default(),
        speeds: RefCell::new(Vec::new()),
        edit: RefCell::new(None),
        history: RefCell::new(Vec::new()),
        move_plan: Arc::new(Mutex::new(None)),
        paused_since: Cell::new(None),
    });
    refresh(&ui, &ctx);
    show_safety(&ui);

    // The sidebar.
    {
        let weak = ui.as_weak();
        ui.on_new_copy(move || {
            if let Some(ui) = weak.upgrade() {
                ui.set_page(0);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_select_session(move |id| {
            if let Some(ui) = weak.upgrade() {
                select_session(&ui, &ctx, id.as_str());
            }
        });
    }
    // Resume: continue an interrupted run from the checkpoint it left; the core refuses any
    // checkpoint that is not this lavoro's own.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_resume_session(move |id, checkpoint| {
            let Some(ui) = weak.upgrade() else { return };
            if ctx.slot.with(|run| run.is_running()) == Some(true) {
                ui.set_error(ui.get_busy_text());
                return;
            }
            ctx.open_when_done.set(false);
            match ctx
                .log
                .begin_resume(id.as_str(), Path::new(checkpoint.as_str()))
            {
                Ok(session) => run_session(&ui, &ctx, &session, true),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    // Repeat: the same folders to the same destination, planned again by the core.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_repeat_session(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let found = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .cloned();
            if let Some(session) = found {
                // A saved task is run again from its file, not re-planned from folders.
                if let Some(task) = session.task.as_deref() {
                    start_task(&ui, &ctx, task);
                    return;
                }
                let chosen: Vec<PathBuf> = session.sources.iter().map(PathBuf::from).collect();
                ctx.open_when_done.set(false);
                start_copy(&ui, &ctx, &chosen, &session.dest, session.verify);
            }
        });
    }
    // Save as task: the name is proposed, the file is written by the core and never overwrites.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_begin_save(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let proposal = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .map(proposed_task_name)
                .unwrap_or_default();
            ui.set_save_name(proposal.into());
            ui.set_save_dir(tasks_dir().to_string_lossy().into_owned().into());
            ui.set_save_message("".into());
            ui.set_saving(true);
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_confirm_save(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let name = ui.get_save_name().to_string();
            match ctx.log.save_as_task(id.as_str(), &tasks_dir(), name.trim()) {
                Ok(path) => {
                    ui.set_save_ok(true);
                    ui.set_save_message(path.to_string_lossy().into_owned().into());
                    ui.set_saving(false);
                    refresh(&ui, &ctx);
                }
                Err(error) => {
                    ui.set_save_ok(false);
                    ui.set_save_message(error.to_string().into());
                }
            }
        });
    }

    // Saved tasks.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_show_tasks(move || {
            if let Some(ui) = weak.upgrade() {
                ui.set_error("".into());
                refresh_tasks(&ui, &ctx);
                ui.set_page(2);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_run_task(move |path| {
            if let Some(ui) = weak.upgrade() {
                start_task(&ui, &ctx, Path::new(path.as_str()));
            }
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_run_config_file(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new()
                    .add_filter("Configurazione TOML", &["toml"])
                    .pick_file();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if let Some(path) = picked {
                        ui.invoke_add_config(path.to_string_lossy().into_owned().into());
                    }
                });
            });
        });
    }

    {
        let weak = ui.as_weak();
        ui.on_show_task_props(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            ui.set_props_title(
                config
                    .file_stem()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default()
                    .into(),
            );
            match property_rows(&config) {
                Ok(rows) => {
                    ui.set_error("".into());
                    ui.set_props(ModelRc::new(VecModel::from(rows)));
                }
                Err(message) => {
                    ui.set_props(ModelRc::new(VecModel::from(Vec::<PropRow>::new())));
                    ui.set_error(message.into());
                }
            }
            ui.set_page(3);
        });
    }

    // Editor (phase 4c): opens a configuration's jobs as drafts; saving writes a proposal beside the
    // file, never over it, and every rule about what a draft may contain is the core's.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_task(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            match job_editor::read_drafts(&config) {
                Ok(drafts) if !drafts.is_empty() => {
                    let names: Vec<SharedString> = drafts
                        .iter()
                        .map(|d| SharedString::from(d.name.as_str()))
                        .collect();
                    ui.set_edit_jobs(ModelRc::new(VecModel::from(names)));
                    ui.set_edit_title(
                        config
                            .file_stem()
                            .map(|n| n.to_string_lossy().into_owned())
                            .unwrap_or_default()
                            .into(),
                    );
                    let state = EditState {
                        config,
                        drafts,
                        index: 0,
                    };
                    load_editor_form(&ui, &state);
                    *ctx.edit.borrow_mut() = Some(state);
                    ui.set_error("".into());
                    ui.set_page(4);
                }
                Ok(_) => ui.set_error("Nessun job da modificare in questo file.".into()),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_select_job(move |index| {
            let Some(ui) = weak.upgrade() else { return };
            if let Some(state) = ctx.edit.borrow_mut().as_mut() {
                state.index = usize::try_from(index)
                    .unwrap_or(0)
                    .min(state.drafts.len().saturating_sub(1));
                load_editor_form(&ui, state);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_edit_save(move || {
            let Some(ui) = weak.upgrade() else { return };
            let guard = ctx.edit.borrow();
            let Some(state) = guard.as_ref() else { return };
            let Some(original) = state.drafts.get(state.index) else {
                return;
            };
            let result = from_slint(ui.get_form())
                .to_draft(original)
                .and_then(|draft| {
                    let out = job_editor::suggest_proposal_path_now(&state.config);
                    job_editor::propose_config_from_path(Some(&state.config), &[draft], &out)
                        .map(|()| out)
                        .map_err(|error| error.to_string())
                });
            match result {
                Ok(out) => {
                    ui.set_edit_ok(true);
                    ui.set_edit_message(out.to_string_lossy().into_owned().into());
                }
                Err(message) => {
                    ui.set_edit_ok(false);
                    ui.set_edit_message(message.into());
                }
            }
        });
    }

    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_show_history(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            let name = config
                .file_stem()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_default();
            show_history_page(&ui, &ctx, name, history_rows(&config));
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_hist_filter_changed(move || {
            let Some(ui) = weak.upgrade() else { return };
            apply_history_filter(&ui, &ctx);
        });
    }
    // Exports exactly what the list shows (the filter applied): a CSV that quietly held rows the
    // person had just filtered out would misstate what they chose to export.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_export_history(move || {
            let Some(ui) = weak.upgrade() else { return };
            let filter = ui.get_hist_filter();
            let shown: Vec<RunLine> = ctx
                .history
                .borrow()
                .iter()
                .filter(|run| passes_filter(filter, run))
                .cloned()
                .collect();
            let text = history_csv(&shown);
            let count = shown.len();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new()
                    .set_file_name("rustcopy-storico.csv")
                    .add_filter("CSV", &["csv"])
                    .save_file();
                let Some(path) = picked else { return };
                let message = match std::fs::write(&path, text) {
                    Ok(()) => format!("{count} esecuzioni esportate in {}", path.display()),
                    Err(error) => {
                        format!("Non sono riuscito a scrivere {}: {error}", path.display())
                    }
                };
                let _ = weak.upgrade_in_event_loop(move |ui| ui.set_hist_message(message.into()));
            });
        });
    }

    // The editor's folder pickers: the native dialog blocks, so it runs on a worker thread, and the
    // chosen path goes into the form only (nothing is written until "Scrivi proposta").
    {
        let weak = ui.as_weak();
        ui.on_edit_browse(move |which| {
            let Some(ui) = weak.upgrade() else { return };
            let current = if which == 0 {
                ui.get_form().source.to_string()
            } else {
                ui.get_form().dest.to_string()
            };
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let mut dialog = rfd::FileDialog::new();
                let start = PathBuf::from(current.trim());
                if start.is_dir() {
                    dialog = dialog.set_directory(&start);
                }
                let Some(path) = dialog.pick_folder() else {
                    return;
                };
                let text = path.to_string_lossy().into_owned();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    let mut form = ui.get_form();
                    if which == 0 {
                        form.source = text.into();
                    } else {
                        form.dest = text.into();
                    }
                    ui.set_form(form);
                });
            });
        });
    }

    // Move, second step: plan what would be deleted (reads only), then delete after a confirmation. The
    // core re-checks the level, the proof of verification and every file; this only runs the two calls.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_check_move(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let found = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .cloned();
            let Some(session) = found else { return };
            ui.set_d_move_busy(true);
            let slot = ctx.move_plan.clone();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let result = plan_a_move(&session);
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    ui.set_d_move_busy(false);
                    match result {
                        Ok(plan) => {
                            ui.set_d_move_text(move_text::plan_text(&plan).into());
                            ui.set_d_move(2);
                            *slot.lock().unwrap_or_else(|p| p.into_inner()) =
                                Some((session.id.clone(), plan));
                        }
                        Err(message) => {
                            ui.set_d_move(4);
                            ui.set_d_move_text(message.into());
                        }
                    }
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_cancel_move(move || {
            let Some(ui) = weak.upgrade() else { return };
            *ctx.move_plan.lock().unwrap_or_else(|p| p.into_inner()) = None;
            ui.set_d_move(1);
            ui.set_d_move_text("".into());
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_confirm_move(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let taken = ctx
                .move_plan
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .take();
            let Some((plan_id, plan)) = taken.filter(|(plan_id, _)| plan_id == id.as_str()) else {
                ui.set_d_move(1);
                return;
            };
            ui.set_d_move_busy(true);
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                // The level is read again from disk: the window may have been open a long time.
                let level = safety::load(&robocopy_ingest::sessions::data_dir());
                let result = moves::execute_move(level, &plan, Confirmation::Confirmed)
                    .map_err(|e| e.to_string());
                let kept = plan.kept();
                if let Ok(outcome) = &result {
                    let log = SessionLog::default_location();
                    let _ = log.record_moved(&plan_id, outcome.deleted, kept);
                }
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    ui.set_d_move_busy(false);
                    match result {
                        Ok(outcome) => {
                            ui.set_d_move(3);
                            ui.set_d_move_text(move_text::outcome_text(&outcome, kept).into());
                        }
                        Err(message) => {
                            ui.set_d_move(4);
                            ui.set_d_move_text(message.into());
                        }
                    }
                });
            });
        });
    }

    // Safety level (RF-Y12): read from the person's own settings, raised only after a confirmation that
    // says what it unlocks, lowered freely, every change logged by the core.
    {
        let weak = ui.as_weak();
        ui.on_show_safety(move || {
            let Some(ui) = weak.upgrade() else { return };
            show_safety(&ui);
            ui.set_safety_confirming(false);
            ui.set_safety_message("".into());
            ui.set_page(9);
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_safety_picked(move |index| {
            let Some(ui) = weak.upgrade() else { return };
            ui.set_safety_unlocks(level_for(index).unlocks().into());
            ui.set_safety_confirming(false);
            ui.set_safety_message("".into());
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_cancel_safety(move || {
            let Some(ui) = weak.upgrade() else { return };
            show_safety(&ui);
            ui.set_safety_confirming(false);
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_apply_safety(move |index, confirmed| {
            let Some(ui) = weak.upgrade() else { return };
            let dir = robocopy_ingest::sessions::data_dir();
            let target = level_for(index);
            if target > safety::load(&dir) && !confirmed {
                // The first press only explains; the second, on the same page, confirms.
                ui.set_safety_confirming(true);
                return;
            }
            let confirmation = if confirmed {
                Confirmation::Confirmed
            } else {
                Confirmation::NotConfirmed
            };
            match safety::set(&dir, target, confirmation) {
                Ok(level) => {
                    show_safety(&ui);
                    ui.set_safety_confirming(false);
                    ui.set_safety_message(format!("Livello ora: {}.", level.name()).into());
                }
                Err(error) => ui.set_safety_message(error.to_string().into()),
            }
        });
    }

    // Schedules (phase 6): the form only builds text; whether a schedule may exist at all is decided by the
    // core (`schedule::install_arguments`, which re-reads the safety level itself), and the command line
    // installs it. Nothing here writes a schedule.
    {
        let weak = ui.as_weak();
        ui.on_schedule_task(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let config = PathBuf::from(path.as_str());
            let name = config
                .file_stem()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_default();
            ui.set_sch_task_name(name.clone().into());
            ui.set_sch_config(path);
            ui.set_sch_name(format!("rustcopy {name}").into());
            ui.set_sch_kind(0);
            ui.set_sch_time("02:00".into());
            ui.set_sch_hours("6".into());
            ui.set_sch_days(ModelRc::new(VecModel::from(vec![false; 7])));
            ui.set_sch_message("".into());
            ui.set_page(10);
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_install_schedule(move |config| {
            let Some(ui) = weak.upgrade() else { return };
            let days_model = ui.get_sch_days();
            let mut days = [false; 7];
            for (i, slot) in days.iter_mut().enumerate() {
                *slot = days_model.row_data(i).unwrap_or(false);
            }
            let spec = match schedule_form::build_spec(
                schedule_form::Recurrence::from_index(ui.get_sch_kind()),
                ui.get_sch_time().as_str(),
                ui.get_sch_hours().as_str(),
                days,
            ) {
                Ok(spec) => spec,
                Err(message) => {
                    ui.set_sch_ok(false);
                    ui.set_sch_message(message.into());
                    return;
                }
            };
            let name = ui.get_sch_name().to_string();
            let config = PathBuf::from(config.as_str());
            run_schedule_command(&ui, move |level| {
                robocopy_ingest::schedule::install_arguments(level, &config, &spec, name.trim())
            });
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_remove_schedule(move || {
            let Some(ui) = weak.upgrade() else { return };
            let name = ui.get_sch_name().to_string();
            run_schedule_command(&ui, move |level| {
                robocopy_ingest::schedule::removal_arguments(level, name.trim())
            });
        });
    }

    // Restore preview (F64): the core runs the CLI with --restore-from --dry-run into a scratch report
    // and reads it back; the result is shown on the report page, clearly marked as a simulation.
    {
        let weak = ui.as_weak();
        ui.on_preview_restore(move |report, workdir| {
            let Some(ui) = weak.upgrade() else { return };
            start_restore_preview(
                &ui,
                PathBuf::from(report.as_str()),
                (!workdir.is_empty()).then(|| PathBuf::from(workdir.as_str())),
            );
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_preview_restore_session(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            let found = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .map(|s| (s.reports.first().cloned(), s.folder.clone()));
            match found {
                Some((Some(report), folder)) => start_restore_preview(&ui, report, Some(folder)),
                _ => ui.set_error(
                    "Questa copia non ha lasciato un report da cui ripristinare.".into(),
                ),
            }
        });
    }

    // Aiuto: static text, plus the guided example (core `example_workspace`, which refuses to overwrite).
    {
        let weak = ui.as_weak();
        ui.on_show_help(move || {
            let Some(ui) = weak.upgrade() else { return };
            let rows: Vec<HelpRow> = help::entries()
                .into_iter()
                .map(|e| HelpRow {
                    heading: e.heading,
                    term: e.term.into(),
                    text: e.text.into(),
                })
                .collect();
            ui.set_help_rows(ModelRc::new(VecModel::from(rows)));
            ui.set_help_message("".into());
            ui.set_page(8);
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_create_example(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let result = match dirs::document_dir() {
                    Some(documents) => robocopy_ingest::example_workspace::create_example_workspace(
                        &documents.join("rustcopy-demo"),
                    )
                    .map_err(|e| match e {
                        robocopy_ingest::errors::IngestError::ExampleWorkspaceAlreadyExists(dir) => {
                            format!(
                                "{} esiste già: un esempio non ne riscrive mai uno. Toglila o usa quella che c'è.",
                                dir.display()
                            )
                        }
                        other => other.to_string(),
                    }),
                    None => Err("Non trovo la cartella Documenti.".to_string()),
                };
                let _ = weak.upgrade_in_event_loop(move |ui| match result {
                    Ok(config) => {
                        ui.set_help_ok(true);
                        ui.set_help_message(
                            format!(
                                "Esempio pronto: {}. Lo trovi tra le attività: provalo con «Esegui».",
                                config.display()
                            )
                            .into(),
                        );
                        ui.invoke_add_config(config.to_string_lossy().into_owned().into());
                    }
                    Err(message) => {
                        ui.set_help_ok(false);
                        ui.set_help_message(message.into());
                    }
                });
            });
        });
    }

    // Credentials (F56): the secret goes from this window straight to Windows' Credential Manager,
    // never to a process argument, and the field is emptied as soon as it has done its one job.
    {
        let weak = ui.as_weak();
        ui.on_show_credentials(move || {
            let Some(ui) = weak.upgrade() else { return };
            ui.set_cred_message("".into());
            ui.set_cred_secret("".into());
            ui.set_page(7);
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_save_credential(move |name, secret| {
            let Some(ui) = weak.upgrade() else { return };
            ui.set_cred_busy(true);
            ui.set_cred_message("".into());
            let name = name.to_string();
            let secret = secret.to_string();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let result = gui_api::set_credential(name.trim(), &secret);
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    ui.set_cred_busy(false);
                    match result {
                        Ok(()) => {
                            // Cleared, not just hidden: nothing of the secret stays in the window.
                            ui.set_cred_secret("".into());
                            ui.set_cred_ok(true);
                            ui.set_cred_message(
                                format!(
                                    "Credenziale «{}» salvata. Usala come keyring:{}.",
                                    name.trim(),
                                    name.trim()
                                )
                                .into(),
                            );
                        }
                        Err(error) => {
                            ui.set_cred_ok(false);
                            ui.set_cred_message(error.to_string().into());
                        }
                    }
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_delete_credential(move |name| {
            let Some(ui) = weak.upgrade() else { return };
            ui.set_cred_busy(true);
            ui.set_cred_message("".into());
            let name = name.to_string();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let result = gui_api::delete_credential(name.trim());
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    ui.set_cred_busy(false);
                    match result {
                        Ok(()) => {
                            ui.set_cred_ok(true);
                            ui.set_cred_message(
                                format!("Credenziale «{}» rimossa.", name.trim()).into(),
                            );
                        }
                        Err(error) => {
                            ui.set_cred_ok(false);
                            ui.set_cred_message(error.to_string().into());
                        }
                    }
                });
            });
        });
    }

    // A report file chosen from disk: read on a worker thread and only ever read. Its own run index
    // sits beside it, so the history of "this report" needs no configuration.
    {
        let weak = ui.as_weak();
        ui.on_open_report_file(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new()
                    .add_filter("Report JSON", &["json"])
                    .pick_file();
                let Some(path) = picked else { return };
                let read = gui_api::read_report(&path).map_err(|e| e.to_string());
                let name = path
                    .file_name()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default();
                let path_text = path.to_string_lossy().into_owned();
                let _ = weak.upgrade_in_event_loop(move |ui| match read {
                    Ok(view) => {
                        let shown: Vec<DetailRow> = report_rows::rows_for(&view)
                            .into_iter()
                            .map(detail_row)
                            .collect();
                        ui.set_error("".into());
                        ui.set_report_name(name.into());
                        ui.set_report_note("".into());
                        ui.set_report_workdir("".into());
                        ui.set_report_path(path_text.into());
                        ui.set_report_rows(ModelRc::new(VecModel::from(shown)));
                        ui.set_page(6);
                    }
                    Err(message) => ui.set_error(message.into()),
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_show_report_history(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            let report = PathBuf::from(path.as_str());
            let name = report
                .file_stem()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_default();
            show_history_page(&ui, &ctx, name, history_of_report(&report));
        });
    }

    // Technical report of the selected lavoro: read on a worker thread, discarded if another lavoro is
    // opened meanwhile (E01).
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_toggle_technical(move |id| {
            let Some(ui) = weak.upgrade() else { return };
            if ui.get_d_show_technical() {
                ui.set_d_show_technical(false);
                return;
            }
            ui.set_d_show_technical(true);
            let reports: Vec<PathBuf> = ctx
                .sessions
                .borrow()
                .iter()
                .find(|s| s.id == id.as_str())
                .map(|s| s.reports.clone())
                .unwrap_or_default();
            let ticket = ctx.details.next();
            let generation = ctx.details.clone();
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let many = reports.len() > 1;
                let mut rows: Vec<report_rows::Row> = Vec::new();
                for report in &reports {
                    if many {
                        rows.push(report_rows::Row {
                            kind: report_rows::Kind::Heading,
                            label: report
                                .parent()
                                .and_then(|p| p.file_name())
                                .map(|n| n.to_string_lossy().into_owned())
                                .unwrap_or_default()
                                + " / "
                                + &report
                                    .file_name()
                                    .map(|n| n.to_string_lossy().into_owned())
                                    .unwrap_or_default(),
                            value: String::new(),
                        });
                    }
                    if let Ok(view) = gui_api::read_report(report) {
                        rows.extend(report_rows::rows_for(&view));
                    }
                }
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if generation.is_current(ticket) {
                        let shown: Vec<DetailRow> = rows
                            .into_iter()
                            .map(|row| DetailRow {
                                kind: match row.kind {
                                    report_rows::Kind::Heading => 0,
                                    report_rows::Kind::Line => 1,
                                    report_rows::Kind::Problem => 2,
                                },
                                label: row.label.into(),
                                value: row.value.into(),
                            })
                            .collect();
                        ui.set_d_rows(ModelRc::new(VecModel::from(shown)));
                    }
                });
            });
        });
    }

    // A configuration file the person chose is remembered (never copied or changed); removing takes it
    // off the list and leaves the file.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_add_config(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            match ctx.log.add_config(Path::new(path.as_str())) {
                Ok(()) => {
                    ui.set_error("".into());
                    refresh_tasks(&ui, &ctx);
                }
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_remove_config(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            match ctx.log.remove_config(Path::new(path.as_str())) {
                Ok(()) => refresh_tasks(&ui, &ctx),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }

    // Recent folders (from the log of lavori): choosing one only fills the form.
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.on_pick_recent_source(move |value| {
            let Some(ui) = weak.upgrade() else { return };
            let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
            push_unique(&mut list, Path::new(value.as_str()));
            set_sources(&ui, &list);
            ui.set_error("".into());
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_pick_recent_dest(move |value| {
            let Some(ui) = weak.upgrade() else { return };
            ui.set_dest(value);
            ui.set_error("".into());
            ui.invoke_clear_check();
        });
    }

    // "Controlla prima" (C03): counts only on press, off the window's thread; an answer for folders or
    // a destination that have changed meanwhile is discarded.
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        let sources = sources.clone();
        ui.on_check_copy(move || {
            let Some(ui) = weak.upgrade() else { return };
            let chosen: Vec<PathBuf> = sources
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .iter()
                .map(PathBuf::from)
                .collect();
            let dest = PathBuf::from(ui.get_dest().trim());
            let ticket = ctx.checks.next();
            let generation = ctx.checks.clone();
            ui.set_check_text("".into());
            ui.set_checking(true);
            let weak = ui.as_weak();
            std::thread::spawn(move || {
                let result = gui_api::check_copy(&chosen, &dest);
                let (text, tone) = check::describe(&result);
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if generation.is_current(ticket) {
                        ui.set_check_text(text.into());
                        ui.set_check_attention(tone == check::Tone::Attention);
                        ui.set_checking(false);
                    }
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_clear_check(move || {
            let Some(ui) = weak.upgrade() else { return };
            ctx.checks.next();
            ui.set_check_text("".into());
            ui.set_checking(false);
        });
    }

    // New copy: add folders. The native dialog blocks, so it runs on a worker thread (RNF-07).
    {
        let weak: Weak<AppWindow> = ui.as_weak();
        let sources = sources.clone();
        ui.on_add_folders(move || {
            let sources = sources.clone();
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folders().unwrap_or_default();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                    for path in &picked {
                        push_unique(&mut list, path);
                    }
                    set_sources(&ui, &list);
                    ui.set_error("".into());
                });
            });
        });
    }
    {
        let weak: Weak<AppWindow> = ui.as_weak();
        let sources = sources.clone();
        ui.on_add_files(move || {
            let sources = sources.clone();
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_files().unwrap_or_default();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                    for path in &picked {
                        push_unique(&mut list, path);
                    }
                    set_sources(&ui, &list);
                    ui.set_error("".into());
                });
            });
        });
    }
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.on_remove_source(move |index| {
            if let Some(ui) = weak.upgrade() {
                let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                if (index as usize) < list.len() {
                    list.remove(index as usize);
                }
                set_sources(&ui, &list);
                ui.set_error("".into());
            }
        });
    }
    {
        let weak = ui.as_weak();
        ui.on_browse_dest(move || {
            let weak = weak.clone();
            std::thread::spawn(move || {
                let picked = rfd::FileDialog::new().pick_folder();
                let _ = weak.upgrade_in_event_loop(move |ui| {
                    if let Some(path) = picked {
                        ui.set_dest(path.to_string_lossy().into_owned().into());
                        ui.set_error("".into());
                        ui.invoke_clear_check();
                    }
                });
            });
        });
    }

    // M13: a folder dropped from Explorer arrives as winit's `DroppedFile`, which Slint does not
    // expose to .slint code (C10).
    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        ui.window().on_winit_window_event(move |_window, event| {
            if let WindowEvent::DroppedFile(path) = event {
                if path.is_dir() || path.is_file() {
                    if let Some(ui) = weak.upgrade() {
                        let mut list = sources.lock().unwrap_or_else(|p| p.into_inner());
                        push_unique(&mut list, path);
                        set_sources(&ui, &list);
                        ui.set_error("".into());
                        ui.set_page(0);
                    }
                }
            }
            EventResult::Propagate
        });
    }

    {
        let weak = ui.as_weak();
        let sources = sources.clone();
        let ctx = ctx.clone();
        ui.on_start_copy(move || {
            let Some(ui) = weak.upgrade() else { return };
            let chosen: Vec<PathBuf> = sources
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .iter()
                .map(PathBuf::from)
                .collect();
            let dest = ui.get_dest().to_string();
            let verify = (ui.get_verify() || ui.get_move_mode())
                .then(|| algorithm_for(ui.get_verify_algo()));
            ctx.open_when_done.set(ui.get_open_when_done());
            start_copy(&ui, &ctx, &chosen, &dest, verify);
        });
    }
    {
        let ctx = ctx.clone();
        let weak = ui.as_weak();
        ui.on_stop_copy(move || {
            // A paused copy cannot see the stop request: resume it first.
            if ctx.paused_since.take().is_some() {
                ctx.slot
                    .with(|run| suspend::set_suspended(run.pid(), false));
                if let Some(ui) = weak.upgrade() {
                    ui.set_paused(false);
                }
            }
            ctx.slot.with(|run| run.request_stop());
        });
    }

    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_toggle_pause(move || {
            let Some(ui) = weak.upgrade() else { return };
            let pausing = ctx.paused_since.get().is_none();
            let touched = ctx
                .slot
                .with(|run| suspend::set_suspended(run.pid(), pausing))
                .unwrap_or(0);
            if touched == 0 {
                ui.set_error("Non sono riuscito a mettere in pausa la copia.".into());
                return;
            }
            if pausing {
                ctx.paused_since.set(Some(std::time::Instant::now()));
            } else {
                ctx.paused_since.set(None);
            }
            ui.set_paused(pausing);
            ui.set_error("".into());
        });
    }

    // E11/E12: a configuration handed over by the Explorer extension (first or second launch).
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        ui.on_external_open(move |path| {
            let Some(ui) = weak.upgrade() else { return };
            if ctx.slot.with(|run| run.is_running()) == Some(true) {
                ui.set_error(ui.get_busy_text());
                return;
            }
            ctx.open_when_done.set(false);
            match ctx.log.begin_from_config(Path::new(path.as_str())) {
                Ok(session) => run_session(&ui, &ctx, &session, false),
                Err(error) => ui.set_error(error.to_string().into()),
            }
        });
    }
    #[cfg(windows)]
    {
        let weak = ui.as_weak();
        single_instance::listen(INSTANCE_TAG, move |message| {
            let request = single_instance::parse(&message);
            let _ = weak.upgrade_in_event_loop(move |ui| {
                let _ = ui.show();
                match request {
                    Some(Request::OpenConfig(path)) => {
                        ui.invoke_external_open(path.to_string_lossy().into_owned().into());
                    }
                    Some(Request::Activate) => {}
                    // Never silent: a refused request is shown, not swallowed.
                    None => ui.set_error(ui.get_refused_request_text()),
                }
            });
        });
    }
    if let Some(path) = single_instance::auto_config_arg(&args) {
        ui.invoke_external_open(path.into());
    }

    // Progress, at 250 ms, on the UI thread: a small file read and `try_wait` (E01, E02). One timer for
    // the one resource, so replies cannot overlap.
    let timer = Timer::default();
    {
        let weak = ui.as_weak();
        let ctx = ctx.clone();
        timer.start(TimerMode::Repeated, Duration::from_millis(250), move || {
            let Some(ui) = weak.upgrade() else { return };
            if let Some(since) = ctx.paused_since.get() {
                if since.elapsed() >= suspend::PAUSE_LIMIT {
                    ctx.slot.with(|run| suspend::set_suspended(run.pid(), false));
                    ctx.paused_since.set(None);
                    ui.set_paused(false);
                    ui.set_error(
                        "La pausa è durata troppo (10 minuti): la copia riprende da sola, perché una condivisione di rete può chiudere una connessione ferma da troppo tempo."
                            .into(),
                    );
                }
            }
            if let Some(sample) = ctx.slot.with(|run| run.progress()).flatten() {
                ui.set_fraction(running_fraction(sample.fraction()));
                ui.set_files_done_text(sample.files_done.to_string().into());
                ui.set_files_total_text(
                    sample
                        .files_total
                        .map_or("?".to_string(), |t| t.to_string())
                        .into(),
                );
                ui.set_speed_text(format::human_speed(sample.throughput_mbps).into());
                ui.set_batch_label(match (sample.batch_index, sample.batch_total) {
                    (Some(index), Some(total)) if total > 1 => {
                        format!("Job {index} di {total}").into()
                    }
                    _ => "".into(),
                });
                ui.set_eta_text(
                    sample
                        .eta_seconds()
                        .map_or(String::new(), format::human_duration)
                        .into(),
                );
                let mut speeds = ctx.speeds.borrow_mut();
                speeds.push(sample.throughput_mbps);
                let excess = speeds.len().saturating_sub(format::CHART_SAMPLES);
                speeds.drain(..excess);
                ui.set_chart_commands(format::chart_path(&speeds, 240.0, 56.0).into());
                ui.set_current_file(sample.current_file.unwrap_or_default().into());
            }
            if let Some(done) = ctx.slot.with(|run| run.finished()).flatten() {
                ctx.slot.take();
                ctx.paused_since.set(None);
                ui.set_paused(false);
                ui.set_running(false);
                let id = ctx.running_id.borrow_mut().take();
                if let Some(id) = id {
                    let state = ctx.log.finish(&id, done.exit_code);
                    refresh(&ui, &ctx);
                    select_session(&ui, &ctx, &id);
                    announce_finish(&ui, &ctx, &id, state.ok());
                }
            }
        });
    }

    // Tray icon (the `system-tray` feature of Slint must stay enabled): left click or "Apri" brings
    // the window back; "Esci" quits.
    let tray = AppTray::new()?;
    {
        let weak = ui.as_weak();
        tray.on_show_window(move || {
            if let Some(ui) = weak.upgrade() {
                let _ = ui.show();
            }
        });
        tray.on_quit(|| {
            let _ = slint::quit_event_loop();
        });
    }
    tray.show()?;
    if std::env::var_os("RUSTCOPY_UI_DARK").is_some() {
        ui.set_force_dark(true);
    }

    ui.show()?;
    slint::run_event_loop_until_quit()
}
